### ISSUE TITLE
Import/upload app settings from .env file

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azureappservice#639] opened 2018-10-12 17:52 UTC
Similar to how Functions uploads settings: right-click on app settings, choose "import from .env..."

I'm not familiar enough with the variations of the format, but the extension should support with and without `export` statements.

**Comment by EricJizbaMSFT** [comment] 2018-10-12 17:57
@fiveisprime duplicate of https://github.com/Microsoft/vscode-azureappservice/issues/386?

**Comment by nnja** [comment] 2018-10-12 19:39
@EricJizbaMSFT Close, but quite since #386 requests JSON as a format. A typical `.env` file looks like this for local use:

```shell
# Comment
EXPORT KEY="VALUE"
EXPORT KEY1="VALUE1"

# Quotes are optional if there are no special characters in the value.
EXPORT KEY2="VALUE2"

```
This allows you to run `source .env` from the command line to load all the env variables.

Or like 

```shell
# Comment
KEY=VALUE
KEY1=VALUE1
KEY2=VALUE2
```

for use with [Docker compose](https://docs.docker.com/compose/env-file/) to allow you to pass environment variables to the container.

**Comment by EricJizbaMSFT** [comment] 2018-10-12 20:37
Thanks for more detail @nnja. I think @nturinski just mentioned json as one possibility, but he cared more about the ability to upload/download app settings regardless of file type. I went ahead and closed that bug as 'duplicate' since '.env' sounds more useful

**Closed** 2018-12-18 21:58 UTC
Labels: P1, feature
