### ISSUE TITLE
Unable to select the App Service plan when creating web apps

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#503] opened 2018-07-10 09:04 UTC
Repro Steps:
1. Click '+' to create a new web app, then enter a valid name ->select 'East Asia' for it -> Select 'Windows'.
2. Check whether there is a choice to select the App Service plan or not.

Expect:
There is a choice to select the App Service plan.

Actual:
There is no choice to select the App Service plan. 

More Info:
The default pricing tier is Free. In this case, customers cannot create deployment slots with error in VS Code like below.
![error](https://user-images.githubusercontent.com/34729092/42499747-1b8bdfbe-841f-11e8-9143-fe0d46f49835.png)

**Comment by EricJizbaMSFT** [comment] 2018-07-11 17:36
Closing as duplicate of https://github.com/Microsoft/vscode-azureappservice/issues/497

**Closed by EricJizbaMSFT** 2018-07-11 17:36 UTC
Labels: CTI, duplicate
