### ISSUE TITLE
python django container (in Azure WebApps) remote debugging

### ISSUE THREAD

**Issue by nagarjunr** [microsoft/vscode-azureappservice#1608] opened 2020-06-22 07:26 UTC
When can we have the debugging supported for python apps as it is quite popular for various full stack projects?. 

Action: appService.StartRemoteDebug
Error type: Error
Error Message: Azure Remote Debugging is currently only supported for Node.js apps on Linux.

Version: 0.17.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.getRemoteDebugLanguage extension.bundle.js:164:197941
extension.bundle.js:309:557320extension.bundle.js:309:557320
fulfilled extension.bundle.js:309:556557
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-06-22 20:52
Dupe of https://github.com/microsoft/vscode-azureappservice/issues/1523. We have some support already - you can change the VS Code setting "appService.enablePythonRemoteDebugging" to try it out

**Closed by EricJizbaMSFT** 2020-06-22 20:52 UTC
