### ISSUE TITLE
ECONNRESET trying azure deploy webapp VS Code

### ISSUE THREAD

**Issue by brandonr1** [microsoft/vscode-azureappservice#2194] opened 2022-04-03 14:12 UTC
Using VS Code, on my webapp's publish folder I select "Deploy to web app", after running for a while it reports ECONNRESET in the lower right popup.  I've logged out/in, rebooted, you name it.  After searching it appears v1.66 is the cause that many others are running into here.  I was literally deploying fine yesterday then it just broke in an instance.  Is it VS Code, an Azure extension, ??

Webapp I'm using is based off a basic asp.net core 3.1 project used as an example.

Very annoying, but I ended up using az webapp up to get my updated code deployed.  Which also seems to have the problem that the runtime cannot be discovered when I run from my publish folder.  If I run from the project folder it zips all my files and pushes it, which of course fails on the server ( also puts my source publicly viewable...).  To get it to work I copied the csproj file into the publish folder and that satisfied az webapp enough to zip and push the right files.  So, az webapp up needs to honor --runtime as well ( that seems to be a bug currently?)

Similar?
https://github.com/microsoft/vscode/issues/146577
https://github.com/microsoft/vscode-azureappservice/issues/2191

**Comment by sujeetjaiswara** [comment] 2022-04-04 05:03
Same here,

**Comment by foramkumar-parekh** [comment] 2022-04-04 06:14
I am also facing the same issue.

**Comment by nturinski** [comment] 2022-04-04 18:06
It's most likely related to this issue: https://github.com/microsoft/vscode-azurefunctions/issues/2844

VS Code 1.66 upgraded to Node 16 which has been causing deployment issues for both Functions and App Service.  Unfortunately, the only current known workaround is to downgrade VS Code to 1.65.x.  We're currently investigating a proper fix.

**Comment by NicoHoch** [comment] 2022-04-04 21:03
Is this error related to the issue?
22:56:44: Error: request to https://blckt.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: socket hang up

**Comment by alexweininger** [comment] 2022-04-05 20:24
Until a fix is released in VS Code stable (hopefully the next major release), here are some options:
1. Wait for the fix to come in [VS Code Insiders](https://code.visualstudio.com/insiders/)
2. [Deploy via Azure CLI](https://github.com/microsoft/vscode-azurefunctions/issues/2844#issuecomment-1086259916)
3. Downgrade your Azure App Service extension version to `v0.21.1` (Mar 04, 2021), we used a different zip deploy method which seems to be working still. Note: it might not work in environments like WSL or Codespaces, which is why we changed our deploy in `v0.21.2` (Mar 09, 2021).
4. Downgrade to the [VS Code February 2022 release](https://code.visualstudio.com/updates/v1_65), where zip deploy is working as discussed and confirmed above.

---

Here's some information on the bug we suspect is causing the issue with zip deploy.

We suspect that it was a regression in the [libuv library](https://github.com/libuv/libuv) caused by [libuv/libuv@ce15b84](https://github.com/libuv/libuv/commit/ce15b8405e9d01e221f8390475deab4a40d26e38), which was included in Node.JS `16.13.0`.

See [this issue](https://github.com/microsoft/vscode/issues/146470), and specifically [this comment](https://github.com/microsoft/vscode/issues/146470#issuecomment-1087175293) for more information.

**Comment by alexweininger** [comment] 2022-04-05 20:36
Closing as a duplicate of #2191. Follow along there, or the [corresponding Azure Functions issue](https://github.com/microsoft/vscode-azurefunctions/issues/2844) for further updates and discussion.

**Closed by alexweininger** 2022-04-05 20:36 UTC

**Comment by brandonr1** [comment] 2022-04-06 01:27
> It's most likely related to this issue: [microsoft/vscode-azurefunctions#2844](https://github.com/microsoft/vscode-azurefunctions/issues/2844)
> 
> VS Code 1.66 upgraded to Node 16 which has been causing deployment issues for both Functions and App Service. Unfortunately, the only current known workaround is to downgrade VS Code to 1.65.x. We're currently investigating a proper fix.

Thanks, at the moment using az webapp up is handling things, although in a less than ideal manner.

**Comment by alexweininger** [comment] 2022-04-13 19:34
Fix has been released in version https://github.com/microsoft/vscode-azureappservice/releases/tag/v0.23.2 of the extension.
