### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by TechFrozen1** [Microsoft/vscode-azureappservice#573] opened 2018-08-21 03:49 UTC
Repro steps:
<Enter steps to reproduce issue>

Action: appService.showFile
Error type: Error
Error Message: 'D:\home\LogFiles\kudu\trace\2018-08-21T03-48-18_8b406d_010_GET_vfs-LogFiles-kudu-trace_pending.xml' not found.

Version: 0.9.0
OS: win32

**Comment by nturinski** [comment] 2018-08-21 18:13
Hi @TechFrozen1,

Thanks for reporting this issue.  Since this is actually a duplicate of this issue: https://github.com/Microsoft/vscode-azureappservice/issues/538, I'll close this one.

**Closed by nturinski** 2018-08-21 18:13 UTC
