### ISSUE TITLE
Deploying an existing web app bot since VS Code

### ISSUE THREAD

**Issue by 1530277** [microsoft/vscode-azureappservice#1956] opened 2021-02-10 01:27 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to https://overbot01.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET

Version: 0.20.0
OS: linux
OS Release: 5.8.0-41-generic
Product: Visual Studio Code
Product Version: 1.53.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:166:16389
ClientRequest.emit events.js:327:22
TLSSocket.socketErrorListener _http_client.js:426:9
TLSSocket.emit events.js:315:20
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:84:21
```

</details>

**Comment by nturinski** [comment] 2021-02-10 21:57
Please provide repro steps.

**Comment by ejizba** [comment] 2021-02-10 22:00
Dupe of https://github.com/microsoft/vscode-azureappservice/issues/1932

**Closed by ejizba** 2021-02-10 22:00 UTC
Labels: needs more info
