### ISSUE TITLE
Unable to Publish Web App from VS Code to Azure App Service App on learning sandbox

### ISSUE THREAD

**Issue by SuryaPrasanthi** [microsoft/vscode-azureappservice#1992] opened 2021-03-02 17:57 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.CreateWebApp
Error type: AuthorizationFailed
Error Message: The client 'live.com#<username>' with object id 'd53e092c-720a-4f4d-bd77-4550ac8a3b58' does not have authorization to perform action 'Microsoft.Web/serverfarms/read' over scope '/subscriptions/3dea82b3-b58e-4478-a9c9-ee2d973577a8/resourceGroups/appsvc_windows_centralus/providers/Microsoft.Web/serverfarms/appsvc_windows_centralus' or the scope is invalid. If access was recently granted, please refresh your credentials.

Version: 0.20.0
OS: win32
OS Release: 6.3.9600
Product: Visual Studio Code
Product Version: 1.53.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:66146
extension.bundle.js:46:496611extension.bundle.js:46:496611
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by nturinski** [comment] 2021-03-02 19:16
Duplicate of https://github.com/microsoft/vscode-azureappservice/issues/1490

**Comment by neelip** [comment] 2021-04-08 22:45
This issue seems to be different from #1490. Users using the sandbox subscriptions don't have a lot of the access controls which restricts use of the extension as well. 
https://docs.microsoft.com/en-us/azure/role-based-access-control/troubleshooting

**Closed** 2021-04-08 22:48 UTC
Labels: duplicate
