### ISSUE TITLE
Appsetting issue

### ISSUE THREAD

**Issue by surajsingh290** [Microsoft/vscode-azureappservice#944] opened 2019-04-17 14:25 UTC
Repro steps:

1.
2.

Action: appService.appSettings.Add
Error type: BadRequest
Error Message: AppSetting with name 'MICROSOFT_BOT_APP_ID=66cc0dcb-c870-4ac1-b901-00b3635de619 MICROSOFT_BOT_APP_PASSWORD=[}_[-A{]rgSN}/#SR/}a{$=)^:0#::-#1-|&y+:T:&]!#7P[}}- WEBSITE_NODE_DEFAULT_VERSION=8.9.4' is not allowed.

Version: 0.13.0
OS: win32
VS Code Version: 1.33.1

<details>
<summary>Call Stack</summary>

```
module.exports.E.l.pipeline (dist/extension.bundle.js:277:1449893)
s (dist/extension.bundle.js:277:112563)
s (dist/extension.bundle.js:165:26036)
dist/extension.bundle.js:165:27276
o (dist/extension.bundle.js:223:7054)
dist/extension.bundle.js:165:24957
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] (dist/extension.bundle.js:1:521656)
$.module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:253:5461)
$.emit (events.js:182:13)
$.<anonymous> (dist/extension.bundle.js:253:18274)
$.emit (events.js:187:15)
IncomingMessage.<anonymous> (dist/exten

**Comment by nturinski** [comment] 2019-04-17 18:34
Closing as a dupe of https://github.com/Microsoft/vscode-azureappservice/issues/943

**Closed by nturinski** 2019-04-17 18:34 UTC
