### ISSUE TITLE
Cannot read property 'client' of undefined

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azureappservice#830] opened 2019-01-22 00:17 UTC
Repro steps:
- create a new web app, deploy an express app to the site
- choose `Yes` to always deploy the app to the site
- redeploy by right clicking in the explorer viewlet (not the Azure viewlet)

Result:

Action: appService.Deploy
Error type: TypeError
Error Message: Cannot read property 'client' of undefined

Version: 0.11.0
OS: darwin

I can see the `"appService.defaultWebAppToDeploy"` setting being removed from `settings.json` when I right click to deploy!

Before deploy:

![image](https://user-images.githubusercontent.com/1487073/51504837-dd34c100-1d97-11e9-91bf-3440c80cbd03.png)

As soon as I right click to deploy it is gone:

![image](https://user-images.githubusercontent.com/1487073/51504853-f76e9f00-1d97-11e9-80df-ceb923f3c365.png)

**Comment by EricJizbaMSFT** [comment] 2019-01-22 16:36
Closing as duplicate of https://github.com/Microsoft/vscode-azureappservice/issues/822. It only happens on insiders - @nturinski please make sure to file a bug on VS Code

**Closed by EricJizbaMSFT** 2019-01-22 16:36 UTC

**Comment by EricJizbaMSFT** [comment] 2019-01-22 19:14
@nturinski never mind I went ahead and filed the bug on VS Code. Gotta keep the benevolent overlord @chrisdias happy 🙃
