### ISSUE TITLE
Error type: ECONNRESET

### ISSUE THREAD

**Issue by lkmSasanga** [microsoft/vscode-azureappservice#1957] opened 2021-02-10 12:19 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to https://servicecenterapi1.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: write ECONNRESET

Version: 0.20.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.53.0
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:327:22
TLSSocket.socketErrorListener _http_client.js:426:9
TLSSocket.emit events.js:315:20
errorOrDestroy destroy.js:108:12
onwriteError _stream_writable.js:424:5
onwrite _stream_writable.js:445:5
destroy.js:50:7destroy.js:50:7
TLSSocket.Socket._destroy net.js:679:5
TLSSocket.destroy destroy.js:38:8
WriteWrap.onWriteComplete [as oncomplete] stream_base_commons.js:93:12
```

</details>

**Comment by nturinski** [comment] 2021-02-10 21:56
Please provide repro steps.

**Comment by ejizba** [comment] 2021-02-10 22:00
Dupe of https://github.com/microsoft/vscode-azureappservice/issues/1932

**Closed by ejizba** 2021-02-10 22:00 UTC
Labels: needs more info
