### ISSUE TITLE
error deply sprng boot local app

### ISSUE THREAD

**Issue by ariancruz** [microsoft/vscode-azureappservice#1789] opened 2020-09-30 21:23 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 409
Error Message: There is a deployment currently in progress. Please try again when it completes.

Version: 0.19.0
OS: linux
OS Release: 5.4.0-48-generic
Product: Visual Studio Code
Product Version: 1.49.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:309:388829
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:593298
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:223:5
Request.EventEmitter.emit domain.js:475:20
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:228:7
Request.EventEmitter.emit domain.js:475:20
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:312:28
IncomingMessage.emit events.js:228:7
IncomingMessage.EventEmitter.emit domain.js:475:20
endReadableNT _stream_readable.js:1185:12
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment] 2020-10-01 18:46
Please try deploying again while there isn't a deployment in progress.  If that doesn't resolve your issue, please provide repro steps.

**Comment by EricJizbaMSFT** [comment] 2020-10-05 21:21
Dupe of https://github.com/microsoft/vscode-azureappservice/issues/1589

**Closed by EricJizbaMSFT** 2020-10-05 21:21 UTC
Labels: needs more info
