### ISSUE TITLE
[Unstable] Prompt users to enter the password of root@127.0.0.1 when trying to SSH into Web App

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1439] opened 2020-03-11 07:26 UTC
**OS**: Windows
**Build Version**: [20200310.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16076&view=artifacts&type=publishedArtifacts)

**Repro Steps:**
1. Create a new Linux web app --> Deploy a project to this new web app.
2. Select "SSH into Web App" from the new web pp context menu.

**Expect:**
The App Service extension is supposed to enter it for the user.

**Actual:**
[Unstable] it will prompt to enter the password of root@127.0.0.1
![image](https://user-images.githubusercontent.com/34729092/76390366-83d87a00-632a-11ea-9ce9-3b0a45e177b0.png)
Enter "Docker!" manually:
![image](https://user-images.githubusercontent.com/34729092/76392153-352cdf00-632e-11ea-905d-412591804804.png)

**Comment by nturinski** [comment] 2020-03-11 14:52
We might have to increase the delay between entering in terminal commands

**Comment by EricJizbaMSFT** [comment] 2020-03-23 21:57
Closing as duplicate of https://github.com/microsoft/vscode-azureappservice/issues/932

**Closed by EricJizbaMSFT** 2020-03-23 21:57 UTC
Labels: AT-CTI
