### ISSUE TITLE
Cannot deploy this is what happens when I say Report Issue

### ISSUE THREAD

**Issue by kevinclarkadstech** [microsoft/vscode-azureappservice#1705] opened 2020-07-27 00:11 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.18.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.47.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:524220
fulfilled extension.bundle.js:1:522468
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment] 2020-07-27 17:58
Closing as a dupe of https://github.com/microsoft/vscode-azureappservice/issues/1425

**Closed by nturinski** 2020-07-27 17:58 UTC
