### ISSUE TITLE
Error when deploy to web app

### ISSUE THREAD

**Issue by owsis** [Microsoft/vscode-azureappservice#409] opened 2018-04-18 04:26 UTC
Repro steps:
<Enter steps to reproduce issue>

Action: appService.Deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND apptobi.scm.azurewebsites.net apptobi.scm.azurewebsites.net:443

Version: 0.7.1
OS: win32

**Comment by EricJizbaMSFT** [comment] 2018-04-18 17:54
Thanks for reporting! Closing this a dupe of #398

**Closed by EricJizbaMSFT** 2018-04-18 17:54 UTC
Labels: P2, bug
