### ISSUE TITLE
Can't deploy app service from VSCode

### ISSUE THREAD

**Issue by Rildlanster** [microsoft/vscode-azureappservice#2309] opened 2022-08-31 13:16 UTC
Type: <b>Bug</b>

I keep getting errors when trying to deploy an app service from VSCode. 

"The deployment failed with error: There is a deployment currently in progress. Please try again when it completes.. Please take a few minutes to help us improve the deployment experience"

How much time should I wait? How to cancel an ongoing deploy?

thanks

Extension version: 0.24.3
VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (2.57GB free)|
|Process Argv|--crash-reporter-id e5a45e9f-ec8a-4723-8f2d-2d62ce956ca2|
|Screen Reader|no|
|VM|33%|
</details>

**Comment by alexweininger** [comment] 2022-09-01 22:14
> How much time should I wait? 

Since this error is coming from Azure, subsequent deployments should work after waiting a few minutes. Did deploy eventually work for you? 

> How to cancel an ongoing deploy?

Currently there's no way to cancel an ongoing deployment. (#1589)

For now, closing as a duplicate of #1589.

**Closed by alexweininger** 2022-09-01 22:14 UTC
