### ISSUE TITLE
error while deploying my app using web template studio vuejs flask vuetify

### ISSUE THREAD

**Issue by dea398** [microsoft/vscode-azureappservice#1324] opened 2019-12-06 07:47 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 404
Error Message: No log found for '08c780464b7c4d0eaac7564412191993'.

Version: 0.16.2
OS: win32
OS Release: 10.0.19033
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:323:45122extension.bundle.js:323:45122
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311extension.bundle.js:157:27311
o extension.bundle.js:164:7076
extension.bundle.js:157:24982extension.bundle.js:157:24982
$._callback extension.bundle.js:1:580031
$.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:200:13
$.EventEmitter.emit domain.js:471:20
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:205:15
$.EventEmitter.emit domain.js:471:20
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
IncomingMessage.EventEmitter.emit domain.js:471:20
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by nturinski** [comment] 2019-12-10 00:43
Hi @dea398 

Does this happen consistently?  Could you provide repro steps?

**Comment by dea398** [comment] 2019-12-10 00:47
Yeah, all the time. You just need to create a new web template studio project:

CTRL + shift + p
Web Template Studio: Launch
Put any name
Then choose vue.js as front end
Then choose flask as a back end.
Indicate that you are going to need 1 or 2 Master Detail template or Grid Template (any that uses endpoints)

Now run your project (I tried npm and yarn)
When you browse to you master detail pages or grid pages you will receive that error.

**Comment by dea398** [comment] 2019-12-10 01:05
Sorry about previous message that is a problem I see there is in vs code or web template studio but it is not related to azure. The problem I reported about azure only happened once now it is working. It means it is not an error that occur constantly.

Anyway if you can replay my steps and got an error could you identified if there is a problem with VS code or if it is with something else? (the error I got there is about "Request Header Fields Too Large"

**Comment by EricJizbaMSFT** [comment] 2020-02-24 23:11
Closing as dupe of https://github.com/microsoft/vscode-azureappservice/issues/1365

**Closed by EricJizbaMSFT** 2020-02-24 23:11 UTC
