### ISSUE TITLE
VS Code React App Deploy

### ISSUE THREAD

**Issue by sametgunduz** [microsoft/vscode-azureappservice#1973] opened 2021-02-19 21:52 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 409
Error Message: There is a deployment currently in progress. Please try again when it completes.

Version: 0.20.0
OS: darwin
OS Release: 20.3.0
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:66146
extension.bundle.js:46:496611
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by ejizba** [comment] 2021-02-22 20:12
Dupe of https://github.com/microsoft/vscode-azureappservice/issues/1589

**Closed by ejizba** 2021-02-22 20:12 UTC
