### ISSUE TITLE
Redeplou Back

### ISSUE THREAD

**Issue by alexandreoibh** [microsoft/vscode-azureappservice#1905] opened 2020-12-18 15:35 UTC
The issue text was copied to the clipboard.  Please paste it into this window.

**Comment by alexandreoibh** [comment] 2020-12-18 15:35
ok atualização back

**Comment by nturinski** [comment] 2020-12-18 16:48
Closing as a dupe of https://github.com/microsoft/vscode-azureappservice/issues/1906

**Closed by nturinski** 2020-12-18 16:48 UTC
