### ISSUE TITLE
attempting to deploy vue production app failed?

### ISSUE THREAD

**Issue by mcorning** [microsoft/vscode-azureappservice#1377] opened 2020-02-04 20:36 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 404
Error Message: No log found for 'f98a4a11407d47248c0e4c8a4e68d348'.

Version: 0.16.2
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:323:45122extension.bundle.js:323:45122
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311extension.bundle.js:157:27311
o extension.bundle.js:164:7076
extension.bundle.js:157:24982extension.bundle.js:157:24982
$._callback extension.bundle.js:1:580031
$.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by mcorning** [comment] 2020-02-04 20:58
this was my second attempt at deploying production vue app as a web app using vs code. I successfully created my first app using the quickstart. i tried a third time after changing directories, but things got even more confusing, so decided to delete the last two apps. i will try once more, this time using only the vue folder that contains all my vue files (including the dist folder).

**Comment by mcorning** [comment] 2020-02-04 21:34
third attempt completed successfully. 
now i need to run my vue app instead of the "Hey, Node devs" page. 
apparently, hostingstart.html is not called (because it has "Hey, App Service devs!").
are there docs to show me how to call pages (or manage routes)?

**Comment by nturinski** [comment] 2020-02-05 19:51
Hi @mcorning 

Sorry that you were having issues.  The `No Log found for...` error is some intermittent error the platform has sometimes.  Glad that started working at least.

I think you need to deploy only the `dist` folder.  If you right-click on your `dist` folder from your File Explorer, there should be a `Deploy to Web App...` at the bottom of the menu.

![image](https://user-images.githubusercontent.com/5290572/73877556-bd8b0200-480d-11ea-8058-8624b72f33e2.png)

Please give that a shot and let me know if that works!

**Comment by EricJizbaMSFT** [comment] 2020-02-24 23:05
Closing as duplicate of https://github.com/microsoft/vscode-azureappservice/issues/1006

**Closed by EricJizbaMSFT** 2020-02-24 23:05 UTC
