### ISSUE TITLE
Nodejs app fails to deploy from Visual Studio 

### ISSUE THREAD

**Issue by jjmoyaSMFR** [microsoft/vscode-azureappservice#1340] opened 2019-12-30 21:43 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 403
Error Message: Failed with code "403".

Version: 0.16.2
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:501748extension.bundle.js:218:501748
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311extension.bundle.js:157:27311
o extension.bundle.js:164:7076
extension.bundle.js:157:24982extension.bundle.js:157:24982
$._callback extension.bundle.js:1:580031
$.t._callback.t.callback.t.callback [as callback] extension.bundle.js:194:5449
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-01-03 23:15
Closing as dupe of https://github.com/microsoft/vscode-azureappservice/issues/1341

**Closed by EricJizbaMSFT** 2020-01-03 23:15 UTC
