### ISSUE TITLE
Executing 'Configure Deployment Source…' pops up an error after selecting 'GitHub' 

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#594] opened 2018-08-31 09:11 UTC
Repro steps:
1. Right click one web app and select 'Configure Deployment Source...'.
2. Select 'GitHub', then check the result.

Action: appService.ConfigureDeploymentSource
Error type: InvalidResourceType
Error Message: The resource type 'sourceControls' could not be found in the namespace 'Microsoft.Web' for api version '2018-02-01'. The supported api-versions are '2016-03-01,2015-08-01,2015-07-01,2015-06-01,2015-05-01,2015-04-01,2015-02-01,2014-11-01,2014-06-01,2014-04-01,2014-04-01-preview'.

Version: 0.9.1
OS: win32

**Comment by nturinski** [comment] 2018-08-31 18:40
@v-dantch  That's an interesting error... 😮 Do you know if the web app you tested on was part of a new subscription?  Are there any special properties on that web app?

**Comment by v-dantch** [comment] 2018-09-03 08:06
@nturinski The subscription what I used is not a new subscription (Azure Tools Manual Testing 2) and there is no special properties for the web apps.
Please check the web app from https://ms.portal.azure.com/#@72f988bf-86f1-41af-91ab-2d7cd011db47/resource/subscriptions/92be7e56-8a60-427c-a3e3-0ebd54a827a1/resourceGroups/appsvc_rg_windows_centralus/providers/Microsoft.Web/sites/test0903/appServices

**Comment by nturinski** [comment] 2018-09-05 20:26
@v-dantch I was able to reproduce this with my own app and will investigate the cause. Thanks for letting me know!

**Comment by nturinski** [comment] 2018-09-06 23:29
The issue was server side and has been resolved via https://github.com/Azure/azure-sdk-for-node/issues/3517#issuecomment-419271332.

**Closed by nturinski** 2018-09-06 23:29 UTC
Labels: CTI, bug

**Comment by v-dantch** [comment] 2018-09-07 01:13
Got it. Thanks for your update.
