### ISSUE TITLE
No error message when a `dependsOn` task fails during `runPreDeployTask`

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azureappservice#1180] opened 2019-09-18 18:51 UTC
The long-running 'deploying' notification persists after `dotnet` command isn't found with no error message.

**Comment by nturinski** [comment] 2019-09-19 21:26
While that is an example of when this happens, the crux of the problem is that we are not checking for failures of any tasks other than the `preDeployTask` itself.  So if it `dependsOn` another task and that fails, the UI hangs.

**Comment by nturinski** [comment] 2019-09-26 22:29
Related PR https://github.com/microsoft/vscode-azuretools/pull/591

**Comment by nturinski** [comment] 2019-11-06 21:41
Fixed by https://github.com/microsoft/vscode-azuretools/pull/591

**Closed by nturinski** 2019-11-06 21:41 UTC
Labels: P2, bug
