### ISSUE TITLE
Authorization issue

### ISSUE THREAD

**Issue by jaydeeprsakariya** [Microsoft/vscode-azureappservice#879] opened 2019-02-27 07:15 UTC
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: AuthorizationFailed
Error Message: The client 'jaydeep@icodeable.io' with object id '67acacf4-78be-4c11-b966-54ebfca800fa' does not have authorization to perform action 'Microsoft.Web/serverfarms/read' over scope '/subscriptions/3247e57c-5ec6-4b22-b0b1-3a33911fa81f/resourceGroups/AspZeroTest/providers/Microsoft.Web/serverfarms/AspZeroTest'.

Version: 0.12.0
OS: win32

**Comment by EricJizbaMSFT** [comment] 2019-02-27 22:13
Closing as duplicate of https://github.com/Microsoft/vscode-azureappservice/issues/769. We currently require you to have access to the app service plan, but we hope to remove that requirement.

**Closed by EricJizbaMSFT** 2019-02-27 22:13 UTC
