### ISSUE TITLE
Deployment Slots "Error: Invalid Object"

### ISSUE THREAD

**Issue by wilvoss** [Microsoft/vscode-azureappservice#570] opened 2018-08-17 17:05 UTC
\\\ This is a dup. Sorry.
Not exactly sure how to repro this. But I have a deployment slot that is fine when viewed on portal.azure.com, and used to be fine when viewing with VSCode. I removed some files from the server (using the browser editor in the portal) and since then, no deployment slots appear, regardless of whether they are brand new. Instead, I get an Error: Invalid Object line item as a child to the Deployment Slots.
<img width="277" alt="screen shot 2018-08-17 at 10 04 20 am" src="https://user-images.githubusercontent.com/23462508/44279092-03609e80-a205-11e8-89d0-7d1ee87be2ed.png">

I have uninstalled the extensions (both from within the app, and within the file system). I have uninstalled and reinstalled the app itself. I have restarted my machine (Macbook Pro 2017 model).

**Comment by EricJizbaMSFT** [comment] 2018-08-17 17:15
Thanks for reporting - closing as a duplicate of https://github.com/Microsoft/vscode-azureappservice/issues/564. This is a known issue for all slots that started happening a few days ago. We're currently investigating a fix

**Comment by wilvoss** [comment] 2018-08-17 17:16
Awesome, thanks!

**Closed by EricJizbaMSFT** 2018-08-17 17:15 UTC
