### ISSUE TITLE
Service is unavailable while deploying the azure node js  application .

### ISSUE THREAD

**Issue by bhaskar2500** [microsoft/vscode-azureappservice#1700] opened 2020-07-21 15:05 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: postCreateWebApp
Error type: 503
Error Message: The service is unavailable.

Version: 0.17.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.47.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:309:399343extension.bundle.js:309:399343
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:584810
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by spethso** [comment] 2020-07-22 08:44
I am getting the same error and was not able to fix it yet. Therefore, I am guessing this should be an error on Azure. Hope it is getting solved soon. :(

I was using the VS Code Extension and tried to deploy it via the web portal.

**Comment by nturinski** [comment] 2020-07-22 18:26
Yeah, unfortunately this is most likely platform issues that extension doesn't really have any control over.  Here are [troubleshooting tips](https://docs.microsoft.com/azure/app-service/troubleshoot-http-502-http-503) that might be able to help. 

If these don't help, could you please add repro steps?

**Comment by spethso** [comment] 2020-07-22 20:36
Hi @nturinski, thanks for the fast response. Do you mean the platform I am using? That would be MacOS. However, I can try on Windows tomorrow.

For reproduction:

- I had a running web app for the last weeks. It worked quite well. Today, I recognized, that the service seems to be unavailable. A restart did not solve the issue.
- Also, a redeploy was not able to restore a working app.
- After trying with the existing web app. I created a new one using the VS Code extension. The deployment seemed work, however, still, I am getting a service unavailable as the response.
- The app, I tried to deploy is a Node.js application. I selected Node 12 LTS as the environment.

Do you need further information?

**Comment by nturinski** [comment] 2020-07-24 19:18
Hi @spethso

What I mean by platform is the Azure service itself.  Since we're just making API requests to the server, if we get weird errors like 503's, there's not a whole lot the extension itself can do about it 😦 

That being said, do you know if you are able to deploy anything else?  Could you try deploying a sample node-js app, like this? https://github.com/Azure-Samples/nodejs-docs-hello-world

At least we might be able to determine if the issue is with Azure or maybe there's been a change to your project that's causing issues.  Have you tried looking at the deployment logs?  Maybe there's something in there that could offer a hint as to what's going wrong.

**Comment by spethso** [comment] 2020-07-27 13:24
Hi @nturinski,
The platform for the Azure service itself was Linux with Node 12 LTS.
I did not deploy the sample since I had not changed something in my source code from the time it was working until it was not working anymore.

However, as I have tried with the sample app, it worked. So I retried with my app, and it seems to work again. I would assume the error was in the Azure service itself.

Thanks for your help anyway. And sorry for the inconvenience :)

**Comment by nturinski** [comment] 2020-07-27 18:02
@spethso It's no inconvenience at all!  I'm glad that you were able to get your app working-- I'm sorry that you had to go through that frustrating process.  I'll close this for now, but please re-open if you start to experience problems again.

**Closed by nturinski** 2020-07-27 18:02 UTC
Labels: needs more info
