### ISSUE TITLE
Duplicate deployment throws error and blocks me from seeing any deployment

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#755] opened 2018-11-30 20:13 UTC
I can't get a consistent repro, but I've gotten an error like this multiple times:
![screen shot 2018-11-30 at 11 57 22 am](https://user-images.githubusercontent.com/11282622/49312434-0bcda400-f499-11e8-9e63-d49abebc63d3.png)

Maybe we de-dupe deployments just to be careful? Maybe we add the time to the id? idk...

NOTE: Refreshing the deployments node doesn't help. Refreshing the whole web app does some to help.

**Comment by nturinski** [comment] 2019-04-15 21:12
I believe this is a dupe of this https://github.com/Microsoft/vscode-azureappservice/issues/841 but would like confirmation

**Closed** 2019-05-02 22:50 UTC
Labels: P2, bug, duplicate
