### ISSUE TITLE
Node issue on deploying the code to web app

### ISSUE THREAD

**Issue by Swapna076** [microsoft/vscode-azureappservice#1858] opened 2020-11-17 11:06 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.20.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.51.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:52:15223
fulfilled extension.bundle.js:52:13178
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-11-17 19:14
Dupe of https://github.com/microsoft/vscode-azureappservice/issues/1425

**Closed by EricJizbaMSFT** 2020-11-17 19:14 UTC
