### ISSUE TITLE
ECONNRESET error

### ISSUE THREAD

**Issue by abhi-amr** [microsoft/vscode-azureappservice#1960] opened 2021-02-11 10:37 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to https://hetvikdemo.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET

Version: 0.20.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.53.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:327:22
TLSSocket.socketErrorListener _http_client.js:426:9
TLSSocket.emit events.js:315:20
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:84:21
```

</details>

**Comment by ejizba** [comment] 2021-02-11 18:39
Dupe of https://github.com/microsoft/vscode-azureappservice/issues/1932

**Closed by ejizba** 2021-02-11 18:39 UTC
