### ISSUE TITLE
Deployment to Azure Web App is failed, reason: read ECONNRESET

### ISSUE THREAD

**Issue by Zvenigora** [microsoft/vscode-azureappservice#2191] opened 2022-03-31 17:46 UTC
Deployment to Azure App Service works in VS Code **1.65.2** and it fails in VS Code **1.66.0**. Downgrading to version 1.65.2 restores the function.

### Steps:
Login to Azure.
Open Explorer tab.
Right-click on the deployment package and select Deploy to Web App...
Optionally select the Web App and file folder.
Confirm the dialog 'Are you sure you want to deploy to "..."? This will overwrite any previous deployment and cannot be undone'. Select 'Deploy' button.
VS Code starts the deployment.
Check the output tab.

### Actual logs in output tab (ver. 1.66.0)
12:58:09 PM uat-vwusasurvey-staging: Starting deployment...
12:58:11 PM uat-vwusasurvey-staging: Creating zip package...
12:58:50 PM uat-vwusasurvey-staging: Zip package size: 49.5 MB
1:03:38 PM: Error: request to https://uat-vwusasurvey-staging.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET
![image](https://user-images.githubusercontent.com/17765489/161116432-0048b1ce-5498-42ed-8989-81eb9ef0cd20.png)

### Expected logs in the output tab (ver 1.65.2)
11:00:28 a.m. uat-vwusasurvey-staging: Starting deployment...
11:00:30 a.m. uat-vwusasurvey-staging: Creating zip package...
11:01:37 a.m. uat-vwusasurvey-staging: Zip package size: 49.6 MB
11:01:38 a.m. uat-vwusasurvey-staging: Fetching changes.
11:01:38 a.m. uat-vwusasurvey-staging: Cleaning up temp folders from previous zip deployments and extracting pushed zip file C:\local\Temp\zipdeploy\ofydv0ab.zip (47.29 MB) to C:\local\Temp\zipdeploy\extracted
11:01:46 a.m. uat-vwusasurvey-staging: Updating submodules.
11:01:46 a.m. uat-vwusasurvey-staging: Preparing deployment for commit id '7a3cb5db76'.
11:01:47 a.m. uat-vwusasurvey-staging: Generating deployment script.

![image](https://user-images.githubusercontent.com/17765489/161116722-7129f1bd-aabb-4f53-863c-c7523d63cac2.png)

**Comment by chacabuk** [comment] 2022-03-31 20:30
Same here
Azure App Service 0.23.1

**Comment by stevenpua** [comment] 2022-04-01 06:30
I'm getting this as logs on app service

2022-04-01T04:48:17  Startup Request, url: /api/zipdeploy?isAsync=true&author=VS%20Code, method: POST, type: request, pid: 65,1,5, ScmType: None
2022-04-01T04:50:42    Error occurred, type: error, text: Unexpected end of request content., stackTrace:    at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ChunkedEncodingMessageBody.PumpAsync()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ChunkedEncodingMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.CopyToAsyncInternal(Stream destination, CancellationToken cancellationToken)
   at Kudu.Services.Deployment.PushDeploymentController.PushDeployAsync(ArtifactDeploymentInfo deploymentInfo, Boolean isAsync, HttpContext context, JObject requestJson)
   at Kudu.Services.Deployment.PushDeploymentController.ZipPushDeploy()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Kudu.Services.Web.Tracing.TraceMiddleware.Invoke(HttpContext context)
2022-04-01T04:50:42      Outgoing response, type: response, statusCode: 400, statusText: BadRequest

**Comment by alexweininger** [comment] 2022-04-05 20:41
Using this issue as a catch-all for ECONNRESET errors when attempting to deploy a zip in the App Service extension.

Until a fix is released in VS Code stable (hopefully the next major release), here are some options:
1. Wait for the fix to come in [VS Code Insiders](https://code.visualstudio.com/insiders/)
2. [Deploy via Azure CLI](https://github.com/microsoft/vscode-azurefunctions/issues/2844#issuecomment-1086259916)
3. Downgrade your Azure App Service extension version to `v0.21.1` (Mar 04, 2021), we used a different zip deploy method which seems to be working still. Note: it might not work in environments like WSL or Codespaces, which is why we changed our deploy in `v0.21.2` (Mar 09, 2021).
4. Downgrade to the [VS Code February 2022 release](https://code.visualstudio.com/updates/v1_65), where zip deploy is working as discussed and confirmed above.

---

Here's some information on the bug we suspect is causing the issue with zip deploy.

We suspect that it was a regression in the [libuv library](https://github.com/libuv/libuv) caused by [libuv/libuv@ce15b84](https://github.com/libuv/libuv/commit/ce15b8405e9d01e221f8390475deab4a40d26e38), which was included in Node.JS `16.13.0`.

See [this issue](https://github.com/microsoft/vscode/issues/146470), and specifically [this comment](https://github.com/microsoft/vscode/issues/146470#issuecomment-1087175293) for more information.

The Azure Functions and App Service extensions use the same code to zip deploy, so [Azure Functions is facing the same issue](https://github.com/microsoft/vscode-azurefunctions/issues/2844).

**Comment by cemg** [comment] 2022-04-11 07:16
I downgraded my VS Code from latest to 1.64 and after that deployment is working fine.
but latest versions have a timeout problem.

**Comment by alexweininger** [comment] 2022-04-11 23:08
Hi everyone,

I believe to have found a fix for the ECONNRESET error on deployment. If anyone can help verify the fix for me that would be a big help!

Steps to install extension development build:
1. If needed, update VS Code to `1.66.0` or greater.
1. Download the extension .VSIX from our Azure DevOps Pipeline - [Direct download link](https://dev.azure.com/ms-azuretools/_apis/resources/Containers/5753399/vsix?itemPath=vsix%2Fvscode-azureappservice-0.23.2-alpha.vsix) | [View artifacts](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=45132&view=artifacts&pathAsName=false&type=publishedArtifacts)
1. From the command palette (`F1` or `Command/Ctrl + Shift + P`), run the "Extensions: Install from VSIX..." command.
1. Select the downloaded .VSIX file, then reload VS Code as prompted.

Once installed, attempt to deploy your app as normal. Report back and let us know if deployment succeeded/failed. 

Thanks!

**Comment by Zvenigora** [comment] 2022-04-12 15:19
Hi @alexweininger,

Thank you for sharing the link for the fix. Unfortunately, I cannot validate it because I have no permission to download it.

**Comment by Zvenigora** [comment] 2022-04-12 18:53
Hi @alexweininger,
 
It works, thank you.

**Old Environment:**
VS Code 1.66.1
Azure App Service **v0.23.1**

Result: Socket hang up after 16 minutes.
![image](https://user-images.githubusercontent.com/17765489/163032772-14795b53-9907-4ad0-ac52-cff3587f6122.png)

**New Environment:**
VS Code 1.66.1
Azure App Service **v0.23.2-alpha**

Result: Deployment successful

![image](https://user-images.githubusercontent.com/17765489/163032978-0f8fcf45-86cc-4558-b637-eb41ec616e9b.png)

**Comment by alexweininger** [comment] 2022-04-12 19:07
@Zvenigora thank you for verifying the fix!

**Closed** 2022-04-12 19:54 UTC
Labels: external

**Comment by faceoffers28** [comment] 2022-04-12 22:08
@alexweininger The latest fix worked for me. Thanks!

**Comment by alexweininger** [comment] 2022-04-12 22:36
@faceoffers28 Awesome, thanks! ❤️

**Comment by faceoffers28** [comment] 2022-04-13 00:09
@alexweininger Some items don't appear to be copying over to Azure. What did you change? My project is working locally as expected. When I deploy to Azure using VSC, some items that were there before are now missing.

**Comment by alexweininger** [comment] 2022-04-13 00:21
> Some items don't appear to be copying over to Azure. What did you change? My project is working locally as expected. When I deploy to Azure using VSC, some items that were there before are now missing.

@faceoffers28 Nothing in terms of what files are deployed should have changed. The only change is https://github.com/microsoft/vscode-azuretools/pull/1114

**Comment by alexwolfmsft** [comment] 2022-04-13 19:24
Just wanted to comment that I have also verified that this latest build fixes the issue, thanks.

**Comment by alexweininger** [comment] 2022-04-13 19:32
Fix has been released in version https://github.com/microsoft/vscode-azureappservice/releases/tag/v0.23.2 of the extension.
