### ISSUE TITLE
cannot deploy to azure app service

### ISSUE THREAD

**Issue by songpr** [microsoft/vscode-azureappservice#1446] opened 2020-03-19 08:17 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400 Bad Request
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

Version: 0.16.3
OS: linux
OS Release: 4.19.84-microsoft-standard
Product: Visual Studio Code
Product Version: 1.43.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:288:373764
rejected extension.bundle.js:288:373312
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by nturinski** [comment] 2020-03-19 17:33
Closing as a dupe of https://github.com/microsoft/vscode-azureappservice/issues/1445

**Closed by nturinski** 2020-03-19 17:33 UTC
