### ISSUE TITLE
deployment from VSC failed

### ISSUE THREAD

**Issue by chinchilak** [microsoft/vscode-azureappservice#1772] opened 2020-09-12 09:58 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.18.0
OS: win32
OS Release: 6.1.7601
Product: Visual Studio Code
Product Version: 1.49.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:524220
fulfilled extension.bundle.js:1:522468
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-09-15 19:49
Dupe of https://github.com/microsoft/vscode-azureappservice/issues/1425

**Closed by EricJizbaMSFT** 2020-09-15 19:49 UTC
