### ISSUE TITLE
[Unstable]Fail to access the generated deployed link in 'OUTPUT' 

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#400] opened 2018-04-13 09:20 UTC
Repro Steps:
1. Create a new web app.
2. Deploy a file to the new web app.
3. Open the link in 'OUTPUT' after succeeding to deploy.
4. Check whether the link can be accessed or not in browser.

Expect:
The link can be accessed.

Actual:
Display 'You do not have permission to view this directory or page'.
![no-permission](https://user-images.githubusercontent.com/34729092/38726101-be10ceb4-3ef8-11e8-853e-ec13a8ed0a09.png)

**Comment by nturinski** [comment] 2018-04-13 18:39
@v-dantch Thank you for reporting this issue.  

The link is correct, but the problem is the project that was deployed did not build correctly.  Because the project is broken, the server responds that 'You do not have permission to view this directory or page'. because there is no index.html to serve, so it attempts to direct you to the wwwroot directory, which you wouldn't have access to unless you were logged in.

As this is an issue with deployment and not the actual link being broken, I'll go ahead and close this.

**Closed by nturinski** 2018-04-13 18:39 UTC
