### ISSUE TITLE
WebJobs created in a Deployment Slot do not get displayed

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-azureappservice#62] opened 2017-09-18 23:13 UTC
If a WebJob is created in a Deployment Slot, it is not displayed with the web app's WebJobs

**Comment by EricJizbaMSFT** [comment] 2019-02-20 23:12
Closing as dupe of https://github.com/Microsoft/vscode-azureappservice/issues/402

**Closed by EricJizbaMSFT** 2019-02-20 23:12 UTC
Labels: P3, bug
