### ISSUE TITLE
Can't deploy to azure web app

### ISSUE THREAD

**Issue by trumhemcut** [Microsoft/vscode-azureappservice#468] opened 2018-06-16 08:45 UTC
Repro steps:
<Enter steps to reproduce issue>

Action: appService.Deploy
Error type: Error
Error Message: The page cannot be displayed because an internal server error has occurred.

Version: 0.8.1
OS: darwin

**Comment by EricJizbaMSFT** [comment] 2018-06-20 17:43
Closing as dupe of https://github.com/Microsoft/vscode-azureappservice/issues/464

Please see @nturinski's comment asking for more info in that issue. Any more details would be much appreciated

**Closed by EricJizbaMSFT** 2018-06-20 17:43 UTC
