### ISSUE TITLE
j

### ISSUE THREAD

**Issue by temirbekbalabek** [microsoft/vscode-azureappservice#1982] opened 2021-02-26 08:36 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.CreateWebApp
Error type: ETIMEDOUT
Error Message: request to https://management.azure.com/subscriptions?api-version=2016-06-01 failed, reason: connect ETIMEDOUT 51.116.156.32:443

Version: 0.20.0
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:208:15
TLSSocket.socketErrorListener _http_client.js:399:9
TLSSocket.emit events.js:203:13
emitErrorNT destroy.js:91:8
emitErrorAndCloseNT destroy.js:59:3
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by ejizba** [comment] 2021-02-27 01:12
Closing as dupe of https://github.com/microsoft/vscode-azureappservice/issues/1932. Not the exact same error, but has the same fix

**Closed by ejizba** 2021-02-27 01:12 UTC
