### ISSUE TITLE
Deployment succeeds even after error "The request was aborted" is thrown

### ISSUE THREAD

**Issue by GanjaNationAdmin** [microsoft/vscode-azureappservice#2305] opened 2022-08-11 11:18 UTC
When I right click the app service and choose Deploy to Web, I sometimes get the following error:
Error: The request was aborted

If I try multiple times it finally goes through. 

My environment:
Version: 1.70.0 (user setup)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by nturinski** [comment] 2022-08-11 21:38
Hi @GanjaNationAdmin

Thanks for reporting. It looks like others are running into the same issue: https://github.com/microsoft/vscode/issues/156724

My guess is if you haven't changed anything about your VS Code or the Azure App Service extension, there's just some weirdness going on with the service itself.  Unfortunately App Service sometimes experiences outages beyond the extension's control ☹️

**Comment by ahmedmahmoudR** [comment] 2022-08-13 13:12
Facing the same issue.

**Comment by hannan-m** [comment] 2022-08-18 14:28
Facing the same issue. Tried deploying to UK and Europe regions, same error. @nturinski it's not related to Azure app service. Certainly multiple regions won't have outages or "weirdness" going on. A lot of people started facing this issue and you cannot close the issue just by saying my guess without doing any checking.

**Comment by nturinski** [comment] 2022-08-18 19:10
@hannan-m We are looking into it, but unfortunately, the App Service extension is just a dev tool extension that is hitting the App Service REST API to create/deploy Azures resources. 

Looking online, this error seems to occur when a secure channel couldn't be created so maybe this is something we can try to mitigate. Are you also able to deploy after multiple attempts?

Have you been successfully able to deploy from other methods such as the Azure CLI?

**Comment by hannan-m** [comment] 2022-08-18 19:48
After some checking around, the deployment still succeeds even after the VS code error `The request was aborted`. I checked in Azure App server logs and the status was successful. Unable to figure out why VS code Azure extension is given the error in the first place.

**Comment by nturinski** [comment] 2022-08-18 20:29
Thanks, that's a helpful insight. I'll try to see where this request was aborted error is being thrown. We may be able to do something to handle this.

**Comment by tushaar9027** [comment] 2022-08-21 19:48
I am facing the same issue....and sometimes code also doesn't get deployed

**Comment by Rildlanster** [comment] 2022-08-31 14:01
Same here, but the frequency of this error got relatively high since yesterday, 08/31/2022.

**Comment by alexweininger** [comment] 2022-09-02 19:46
Hi everyone, I am able to reproduce this issue when deploying large apps (over 100MB). We've identified the cause and proposed a fix in https://github.com/microsoft/vscode-azuretools/pull/1230. I will update once this is merged and released.

**Comment by alexweininger** [comment] 2022-09-07 18:47
Reopening until we get the fix merged in

**Closed** 2022-09-08 15:46 UTC
Labels: bug, P0, deploy errors

**Comment by alexweininger** [comment] 2022-09-26 17:10
Fix for this bug has been released in https://github.com/microsoft/vscode-azureappservice/releases/tag/v0.24.4
