### ISSUE TITLE
Error when creating new app

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azureappservice#544] opened 2018-07-31 20:46 UTC
Repro steps:
Seen while creating a new webapp. Error occurred after entering the app name and before attempting to load locations.

Action: appService.Deploy
Error type: object
Error Message: `{"key":"1","value":{"_creator":null,"_nextState":null,"_state":{"name":"error","done":null,"then":null},"_value":{},"_listeners":null,"_isException":false,"_errorId":7}}`

More from the VS Code console:

```sh
  ERR Entry not found in cache.: Error: Entry not found in cache.
	at Logger.createError (C:\Users\maherna\.vscode\extensions\ms-vscode.azure-account-0.4.2\node_modules\ms-rest-azure\node_modules\adal-node\lib\log.js:201:13)
	at TokenRequest.<anonymous> (C:\Users\maherna\.vscode\extensions\ms-vscode.azure-account-0.4.2\node_modules\ms-rest-azure\node_modules\adal-node\lib\token-request.js:524:40)
	at C:\Users\maherna\.vscode\extensions\ms-vscode.azure-account-0.4.2\node_modules\ms-rest-azure\node_modules\adal-node\lib\token-request.js:147:20
	at C:\Users\maherna\.vscode\extensions\ms-vscode.azure-account-0.4.2\node_modules\ms-rest-azure\node_modules\adal-node\lib\cache-driver.js:354:7
	at C:\Users\maherna\.vscode\extensions\ms-vscode.azure-account-0.4.2\node_modules\ms-rest-azure\node_modules\adal-node\lib\cache-driver.js:223:9
	at C:\Users\maherna\.vscode\extensions\ms-vscode.azure-account-0.4.2\node_modules\ms-rest-azure\node_modules\adal-node\lib\cache-driver.js:163:5
	at MemoryCache.find (C:\Users\maherna\.vscode\extensions\ms-vscode.azure-account-0.4.2\node_modules\adal-node\lib\memory-cache.js:89:3)
	at init.then (C:\Users\maherna\.vscode\extensions\ms-vscode.azure-account-0.4.2\out\src\azure-account.js:76:25)
	at <anonymous>
```

Version: 0.9.0
OS: win32

**Comment by EricJizbaMSFT** [comment] 2018-08-01 17:53
Closing as a dupe of https://github.com/Microsoft/vscode-azureappservice/issues/529

Thanks for reporting!

**Closed by EricJizbaMSFT** 2018-08-01 17:53 UTC
Labels: P1, bug
