### ISSUE TITLE
not deploy!!!!!!

### ISSUE THREAD

**Issue by miguelito15tk** [Microsoft/vscode-azureappservice#968] opened 2019-04-30 21:19 UTC
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Error: spawn git ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
	at onErrorNT (internal/child_process.js:406:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)

Version: 0.13.1
OS: win32
VS Code Version: 1.33.1

<details>
<summary>Call Stack</summary>

```
Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
onErrorNT (internal/child_process.js:406:16)
process._tickCallback (internal/process/next_tick.js:63:19)
Object.<anonymous> (dist/extension.bundle.js:333:824733)
Generator.throw (<anonymous>)
a (dist/extension.bundle.js:333:824407)
```

</details>

**Comment by nturinski** [comment] 2019-04-30 21:20
Closing as a duplicate of https://github.com/Microsoft/vscode-azureappservice/issues/967

**Closed by nturinski** 2019-04-30 21:20 UTC
