### ISSUE TITLE
There is no "Reset default" button when deploying the project to another web app

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureappservice#1456] opened 2020-03-25 06:13 UTC
**OS:** Win
**Build:** [20200324.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16628&view=results)

**Repro Steps:**
1. Right click a Web App --> Deploy to Web App...
2. "Always deploy the workspace...to..." --> Select Yes
3. Right click another Web App to deploy again.

**Expect:**
Display the notification to reset default.
![image](https://user-images.githubusercontent.com/57662131/77497576-a02af980-6e88-11ea-9f76-66608eba3d90.png)

**Actual:**
There is no "Reset default" button when deploying the project to another web app.

**More Info:**
This issue doesn't reproduce by clicking deploy button or command line.

**Comment by EricJizbaMSFT** [comment] 2020-03-30 21:49
Closing this as by design. The main purpose of the "Reset default" button is to improve discoverability and make sure people know how to deploy to a different web app when they have a default set. In this case, they already know how to deploy to a different web app

**Closed by EricJizbaMSFT** 2020-03-30 21:49 UTC
Labels: AT-CTI

**Comment by v-xinda** [comment] 2020-04-02 01:22
Got it. Thanks for your sharing.
