### ISSUE TITLE
Files node doesn't auto-refresh after swapping production and a deployment slot

### ISSUE THREAD

**Issue by whiskeyjay** [Microsoft/vscode-azureappservice#250] opened 2017-12-15 21:55 UTC
After the swap, files node should auto-refresh to reflect the changes.

**Comment by EricJizbaMSFT** [comment] 2018-04-04 17:50
Closing as dupe of https://github.com/Microsoft/vscode-azureappservice/issues/375

**Closed by EricJizbaMSFT** 2018-04-04 17:50 UTC
Labels: bug
