### ISSUE TITLE
request to redacted:url failed, reason: unable to get local issuer certificate

### ISSUE THREAD

**Issue by swetlana11** [microsoft/vscode-azureappservice#2481] opened 2023-05-11 10:46 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
Error Message: request to redacted:url failed, reason: unable to get local issuer certificate

Version: 0.24.8
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.78.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:4191476
```

</details>

**Comment by alexweininger** [comment] 2023-05-11 17:29
Closing as duplicate of #2476

**Closed by alexweininger** 2023-05-11 17:29 UTC
Labels: info-needed
