### ISSUE TITLE
Error Deploying an App

### ISSUE THREAD

**Issue by Ayush434** [microsoft/vscode-azureappservice#1493] opened 2020-04-16 22:28 UTC
The issue text was copied to the cli

Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.CreateWebApp
Error type: AuthorizationFailed
Error Message: The client 'v-aymeht@microsoft.com' with object id '6bd9cbf2-b901-4da8-a29e-2562876b585b' does not have authorization to perform action 'Microsoft.Web/serverfarms/read' over scope '/subscriptions/8a1129f7-9929-4811-ac47-dd376389c727/resourceGroups/appsvc_linux_centralus/providers/Microsoft.Web/serverfarms/appsvc_linux_centralus' or the scope is invalid. If access was recently granted, please refresh your credentials.

Version: 0.16.5
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.44.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:3585174extension.bundle.js:225:3585174
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:582086
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>
pboard.  Please paste it into this window.

**Comment by nturinski** [comment] 2020-04-16 23:25
Thanks for reporting @Ayush434

Closing this as a duplicate of https://github.com/microsoft/vscode-azureappservice/issues/1490.

But you should be able to resolve your issue by right-clicking your subscription node and clicking "Create a New Web App (Advanced)..." It seems that you don't have permissions to use the resource group that we default to, `appsvc_linux_centralus`

**Closed by nturinski** 2020-04-16 23:25 UTC
