### ISSUE TITLE
SSH into Web App Error - App is running but port is unavailable

### ISSUE THREAD

**Issue by cmaronchick** [microsoft/vscode-azureappservice#1261] opened 2019-10-29 22:52 UTC
Repro steps:

1. Just got started with a Node/Express Web App
2. Installed the Azure App Service Extension in VS Code
3. Right Click on my project and select SSH into Web App

Action: appService.StartSsh
Error type: Error
Error Message: Unable to establish connection to application: App is started, but port is unreachable

Version: 0.16.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
TunnelProxy.<anonymous> extension.bundle.js:157:99743
a extension.bundle.js:157:95441
```

</details>

**Comment by cmaronchick** [comment] 2019-10-29 22:55
For what it's worth, trying to connect through the portal failed as well

**Comment by nturinski** [comment] 2019-10-31 18:33
Hi @cmaronchick 

Thanks for reporting.  Is this still failing for you, even on the portal?  Have you enabled remote debugging?  I know that Azure only exposes one port for proxies and that could be affecting being able to SSH into the web app.

**Comment by nturinski** [comment] 2019-11-21 23:25
Closing as dupe of https://github.com/microsoft/vscode-azureappservice/issues/1011

**Closed by nturinski** 2019-11-21 23:25 UTC
Labels: needs more info
