### ISSUE TITLE
Support deploying to App Service Environment

### ISSUE THREAD

**Issue by raf02** [Microsoft/vscode-azureappservice#449] opened 2018-05-28 20:10 UTC
Repro steps:
1.  Right click on the desired app service instance and select 'Deploy to Web App'
2.  Select folder to deploy
3.  see the following output and then deployment fails:
4:05:55 PM p01d17101014001: Creating zip package...
4:05:57 PM p01d17101014001: Starting deployment...
Error: getaddrinfo ENOTFOUND p01d17101014001.scm.azurewebsites.net p01d17101014001.scm.azurewebsites.net:443

Action: appService.Deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND p01d17101014001.scm.azurewebsites.net p01d17101014001.scm.azurewebsites.net:443

Version: 0.8.1
OS: win32

**Comment by fiveisprime** [comment] 2018-05-29 16:16
I was thinking maybe the endpoint wasn't available immediately after creation, but I can't seem to resolve the URL still. Is the app still available or did you delete it?

**Comment by raf02** [comment] 2018-05-29 16:25
The app service instance is still there (empty as no app has been deployed yet).  And the vs code extension is able to find it - it just isn't able to deploy there.  

![image](https://user-images.githubusercontent.com/8889938/40671886-236b4792-633b-11e8-8078-6517ce7c171f.png)

**Comment by fiveisprime** [comment] 2018-05-29 16:36
The fact that the DNS isn't resolving makes me think you're right about the URL being created wrong (or some step being missed). I created a similarly named app and everything worked as intended.

I'll report this to the app service folks. Try creating a new app in the same plan and see if that one works correctly.

Sorry for the issues! :(

**Comment by EricJizbaMSFT** [comment] 2018-05-31 16:09
@raf02 If you go to the App Service in the portal, scroll down to the 'Advanced Tools' section and hit 'go' - what URL does it take you to? 
![screen shot 2018-05-31 at 9 05 17 am](https://user-images.githubusercontent.com/11282622/40793658-dd5f9d3e-64b1-11e8-9c11-aec3e8351dd8.png)
Normally it would take you to the URL listed above (p01d17101014001.scm.azurewebsites.net), but I'm curious if you have something different. This could happen if you are using an App Service Environment or other custom domain stuff.

**Comment by raf02** [comment] 2018-05-31 17:07
Hi Eric, 

The url is: https://p01d17101014001.scm.p01d17101012001.c01.dev.ess.dh.com

Yes, we have an app service environment set up.  I was thinking the app service vs code extension would be able to pick up the appropriate url.  Is that only the case when running a "standard" app service on the shared infrastructure tier?

**Comment by EricJizbaMSFT** [comment] 2018-05-31 17:12
We had a similar issue recently filed on our Azure Functions extension, which shares a lot of the deploy code with this extension: https://github.com/Microsoft/vscode-azurefunctions/issues/381

We don't support deploying to App Service Environments yet, but it's definitely on our backlog and we hope to get it fixed soon

**Comment by raf02** [comment] 2018-05-31 17:56
Thanks @EricJizbaMSFT 

Having the feature would be great.  It would even be helpful just to have some kind of message or indicator that deployment is not available for the resource in ASE in the meantime.

**Closed** 2018-06-05 22:03 UTC
Labels: P1, bug

**Comment by EricJizbaMSFT** [comment] 2018-07-12 23:20
@raf02 FYI we just released an update that should support deploying to ASE's. Thanks for reporting! :)
