### ISSUE TITLE
Zip deploy takes about 10min for a simple express/mongo app

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azureappservice#234] opened 2017-12-13 20:57 UTC
I have a pretty simple Node/Express/Mongo app which takes in excess of 10min to zip deploy.

``` console
git clone https://github.com/glimpse/stickerapp
cd stickerapp
git checkout chrisdias/connect2017
npm install && code-insiders .
```
create a new azure app service using the extension (i used a small linux box, west us)
once created, right click on the app service and (zip) deploy

result: takes about 10 minutes

If i had not been testing this scenario I would have thought it was hung and i would have killed the process.

**Comment by whiskeyjay** [comment] 2017-12-14 03:04
Are you using the latest master or the published version? What's the size of node_modules?

**Comment by chrisdias** [comment] 2017-12-14 03:26
published version, not master. node modules is 116mb on disk according to windows file explorer... i will try with master.

**Comment by chrisdias** [comment] 2017-12-14 04:33
here is what the output looks like for `master`. I used an `S1` app plan.

``` console
Using Subscription "SmartHotel360-Prod (546ac631-883f-4fb4-bff0-b8639ed6e7c8)".
Creating new resource group "cdiasstickerapp12345-rg (westus)"...
Created resource group "cdiasstickerapp12345-rg (westus)".
Creating new App Service plan "cdiasstickerapp12345-plan (S1)"...
Created App Service plan "cdiasstickerapp12345-plan (S1)".
Creating new Web App "cdias-stickerapp-12345"...
Created new Web App "cdias-stickerapp-12345": https://cdias-stickerapp-12345.azurewebsites.net
8:14:06 PM cdias-stickerapp-12345: Creating zip package...
8:15:48 PM cdias-stickerapp-12345: Starting deployment...
8:17:03 PM cdias-stickerapp-12345: Fetching changes.
8:17:09 PM cdias-stickerapp-12345: Fetching changes.
8:17:16 PM cdias-stickerapp-12345: Fetching changes.
8:17:23 PM cdias-stickerapp-12345: Fetching changes.
8:17:29 PM cdias-stickerapp-12345: Fetching changes.
8:17:35 PM cdias-stickerapp-12345: Fetching changes.
8:17:41 PM cdias-stickerapp-12345: Fetching changes.
8:17:47 PM cdias-stickerapp-12345: Fetching changes.
8:17:53 PM cdias-stickerapp-12345: Fetching changes.
8:17:59 PM cdias-stickerapp-12345: Fetching changes.
8:18:05 PM cdias-stickerapp-12345: Fetching changes.
8:18:12 PM cdias-stickerapp-12345: Fetching changes.
8:18:18 PM cdias-stickerapp-12345: Fetching changes.
8:18:24 PM cdias-stickerapp-12345: Fetching changes.
8:18:31 PM cdias-stickerapp-12345: Fetching changes.
8:18:37 PM cdias-stickerapp-12345: Fetching changes.
8:18:43 PM cdias-stickerapp-12345: Fetching changes.
8:18:50 PM cdias-stickerapp-12345: Fetching changes.
8:18:56 PM cdias-stickerapp-12345: Fetching changes.
8:19:02 PM cdias-stickerapp-12345: Fetching changes.
8:19:09 PM cdias-stickerapp-12345: Fetching changes.
8:19:15 PM cdias-stickerapp-12345: Fetching changes.
8:19:22 PM cdias-stickerapp-12345: Fetching changes.
8:19:28 PM cdias-stickerapp-12345: Fetching changes.
8:19:35 PM cdias-stickerapp-12345: Fetching changes.
8:19:41 PM cdias-stickerapp-12345: Fetching changes.
8:19:48 PM cdias-stickerapp-12345: Fetching changes.
8:19:54 PM cdias-stickerapp-12345: Fetching changes.
8:20:00 PM cdias-stickerapp-12345: Preparing deployment for commit id '8461c45dee'.
8:20:06 PM cdias-stickerapp-12345: Running deployment command...
8:20:13 PM cdias-stickerapp-12345: Running deployment command...
8:20:19 PM cdias-stickerapp-12345: Running deployment command...
8:20:24 PM cdias-stickerapp-12345: Running deployment command...
8:20:30 PM cdias-stickerapp-12345: Running deployment command...
8:20:36 PM cdias-stickerapp-12345: Running deployment command...
8:20:43 PM cdias-stickerapp-12345: Running deployment command...
8:20:49 PM cdias-stickerapp-12345: Running deployment command...
8:20:55 PM cdias-stickerapp-12345: Running deployment command...
8:21:01 PM cdias-stickerapp-12345: Running deployment command...
8:21:07 PM cdias-stickerapp-12345: Running deployment command...
8:21:13 PM cdias-stickerapp-12345: Running deployment command...
8:21:19 PM cdias-stickerapp-12345: Running deployment command...
8:21:25 PM cdias-stickerapp-12345: Running deployment command...
8:21:31 PM cdias-stickerapp-12345: Running deployment command...
8:21:37 PM cdias-stickerapp-12345: Running deployment command...
8:21:43 PM cdias-stickerapp-12345: Running deployment command...
8:21:49 PM cdias-stickerapp-12345: Running deployment command...
8:21:56 PM cdias-stickerapp-12345: Running deployment command...
8:22:02 PM cdias-stickerapp-12345: Running deployment command...
8:22:07 PM cdias-stickerapp-12345: Running deployment command...
8:22:13 PM cdias-stickerapp-12345: Running deployment command...
8:22:19 PM cdias-stickerapp-12345: Running deployment command...
8:22:25 PM cdias-stickerapp-12345: Running deployment command...
8:22:31 PM cdias-stickerapp-12345: Running deployment command...
8:22:37 PM cdias-stickerapp-12345: Running deployment command...
8:22:46 PM cdias-stickerapp-12345: Running deployment command...
8:22:52 PM cdias-stickerapp-12345: Running deployment command...
8:22:58 PM cdias-stickerapp-12345: Running deployment command...
8:23:04 PM cdias-stickerapp-12345: Running deployment command...
8:23:10 PM cdias-stickerapp-12345: Running deployment command...
8:23:16 PM cdias-stickerapp-12345: Running deployment command...
8:23:22 PM cdias-stickerapp-12345: Running deployment command...
8:23:29 PM cdias-stickerapp-12345: Running deployment command...
8:23:35 PM cdias-stickerapp-12345: Running deployment command...
8:23:40 PM cdias-stickerapp-12345: Running deployment command...
8:23:46 PM cdias-stickerapp-12345: Running deployment command...
8:23:52 PM cdias-stickerapp-12345: Running deployment command...
8:23:58 PM cdias-stickerapp-12345: Running deployment command...
8:24:04 PM cdias-stickerapp-12345: Running deployment command...
8:24:09 PM cdias-stickerapp-12345: Running deployment command...
8:24:16 PM cdias-stickerapp-12345: Running deployment command...
8:24:21 PM cdias-stickerapp-12345: Running deployment command...
8:24:27 PM cdias-stickerapp-12345: Running deployment command...
8:24:33 PM cdias-stickerapp-12345: Running deployment command...
8:24:39 PM cdias-stickerapp-12345: Running deployment command...
8:24:45 PM cdias-stickerapp-12345: Running deployment command...
8:24:51 PM cdias-stickerapp-12345: Running deployment command...
8:24:57 PM cdias-stickerapp-12345: Running deployment command...
8:25:04 PM cdias-stickerapp-12345: Running deployment command...
8:25:11 PM cdias-stickerapp-12345: Running deployment command...
8:25:17 PM cdias-stickerapp-12345: Running deployment command...
8:25:23 PM cdias-stickerapp-12345: Deployment completed.
```

**Comment by whiskeyjay** [comment] 2017-12-14 22:08
Now there is a workspace setting/app setting combination you can use to exclude the node_modules from the zip file and have them installed on the sever side during deployment:

Set [appService.zipIgnorePattern](https://github.com/Microsoft/vscode-azureappservice/blob/a9e5a300a8be70928782bc967dc92e1f7cfce0ca/package.json#L476) to "node_modules{,/**}" to exclude the folder. That should speed up the zip/upload/unzip process.

You also need to have an app setting "SCM_DO_BUILD_DURING_DEPLOYMENT=true" for Kudu to install the node modules on the server side.

**Comment by whiskeyjay** [comment] 2017-12-15 20:59
This is what I get from deploying the StickerApp with the settings above:

12:54:53 PM jw-test-publish: Creating zip package...
12:55:03 PM jw-test-publish: Starting deployment...
12:55:07 PM jw-test-publish: Fetching changes.
12:55:13 PM jw-test-publish: Running deployment command...
12:55:20 PM jw-test-publish: Running deployment command...
12:55:26 PM jw-test-publish: Running deployment command...
12:55:32 PM jw-test-publish: Running deployment command...
12:55:38 PM jw-test-publish: Running deployment command...
12:55:44 PM jw-test-publish: Running deployment command...
12:55:50 PM jw-test-publish: Running deployment command...
12:55:57 PM jw-test-publish: Running deployment command...
12:56:03 PM jw-test-publish: Running deployment command...
12:56:09 PM jw-test-publish: Running deployment command...
12:56:15 PM jw-test-publish: Running deployment command...
12:56:21 PM jw-test-publish: Running deployment command...
12:56:27 PM jw-test-publish: Running deployment command...
12:56:33 PM jw-test-publish: Running deployment command...
12:56:39 PM jw-test-publish: Running deployment command...
12:56:45 PM jw-test-publish: Running deployment command...
12:56:51 PM jw-test-publish: Running deployment command...
12:56:58 PM jw-test-publish: Running deployment command...
12:57:04 PM jw-test-publish: Running deployment command...
12:57:11 PM jw-test-publish: Running deployment command...
12:57:17 PM jw-test-publish: Running deployment command...
12:57:23 PM jw-test-publish: Running deployment command...
12:57:29 PM jw-test-publish: Running deployment command...
12:57:36 PM jw-test-publish: Running deployment command...
12:57:42 PM jw-test-publish: Running deployment command...
12:57:48 PM jw-test-publish: Running deployment command...
>>>>>> Deployment to "jw-test-publish" completed. <<<<<<

It took 3 minutes from start to complete.

**Comment by chrisdias** [comment] 2018-01-19 01:11
If I include the `node_modules` folder in the zip deployment, this takes about 10min but "just works".  I can browse to the site after deployment.

If I delete `node_modules` and do a zip deployment, it goes fast but the site doesn't work (`service unavailable`).

If I add the setting `appService.zipIgnorePattern` and deploy, It goes fast but site doesn't work.

If i then add the `SCM_DO_BUILD_DURING_DEPLOYMENT` app setting, it takes about 3 min and the site works.

As a user, i have no way of knowing I have to know to set the setting and that I have to create the site and set the app setting before deployment.  

Can we have `zipIgnorePattern` defaulted to `"node_modules{,/**}"` and set the `SCM...` app setting automatically when creating a site?

**Comment by EricJizbaMSFT** [comment] 2018-02-08 22:22
Closing as duplicate of https://github.com/Microsoft/vscode-azureappservice/issues/224

**Closed by EricJizbaMSFT** 2018-02-08 22:22 UTC
Labels: bug
