### ISSUE TITLE
Unable to deploy my React.js app from VSCode

### ISSUE THREAD

**Issue by KarlDreyerJr** [microsoft/vscode-azureappservice#2192] opened 2022-04-02 20:01 UTC
Does this occur consistently? 
Repro steps:

This is a React.js application. I've been working on this for months with no issues at all.  This morning, I attempted to deploy and received the following errors

2:43:59 PM AscentTrading: Starting deployment...
2:44:00 PM AscentTrading: Creating zip package...
2:44:01 PM AscentTrading: Ignoring files from "appService.zipIgnorePattern"
"node_modules{,/**}"
".vscode{,/**}"
2:44:04 PM AscentTrading: Zip package size: 2.47 MB
2:48:52 PM: Error: request to https://[]/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET

When I click on the link above, I get this message : No route registered for '/api/zipdeploy'
1.Create production build 
2. Right click and choose deploy

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to redacted:url failed, reason: read ECONNRESET

Version: 0.23.1
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.66.0
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:2848728
```

</details>

**Comment by alexweininger** [comment] 2022-04-05 20:26
Until a fix is released in VS Code stable (hopefully the next major release), here are some options:
1. Wait for the fix to come in [VS Code Insiders](https://code.visualstudio.com/insiders/)
2. [Deploy via Azure CLI](https://github.com/microsoft/vscode-azurefunctions/issues/2844#issuecomment-1086259916)
3. Downgrade your Azure App Service extension version to `v0.21.1` (Mar 04, 2021), we used a different zip deploy method which seems to be working still. Note: it might not work in environments like WSL or Codespaces, which is why we changed our deploy in `v0.21.2` (Mar 09, 2021).
4. Downgrade to the [VS Code February 2022 release](https://code.visualstudio.com/updates/v1_65), where zip deploy is working as discussed and confirmed above.

---

Here's some information on the bug we suspect is causing the issue with zip deploy.

We suspect that it was a regression in the [libuv library](https://github.com/libuv/libuv) caused by [libuv/libuv@ce15b84](https://github.com/libuv/libuv/commit/ce15b8405e9d01e221f8390475deab4a40d26e38), which was included in Node.JS `16.13.0`.

See [this issue](https://github.com/microsoft/vscode/issues/146470), and specifically [this comment](https://github.com/microsoft/vscode/issues/146470#issuecomment-1087175293) for more information.

**Comment by alexweininger** [comment] 2022-04-05 20:36
Closing as a duplicate of #2191. Follow along there, or the [corresponding Azure Functions issue](https://github.com/microsoft/vscode-azurefunctions/issues/2844) further updates and discussion.

**Closed by alexweininger** 2022-04-05 20:36 UTC
