### ISSUE TITLE
Cannot deploy my web application.  I get the following error:

### ISSUE THREAD

**Issue by ekyros** [Microsoft/vscode-azureappservice#388] opened 2018-04-06 11:53 UTC
Repro steps:
<Enter steps to reproduce issue>

Action: appService.Deploy
Error type: Error
Error Message: The page you are looking for cannot be displayed because an invalid method (HTTP verb) is being used.

Version: 0.7.0
OS: win32

**Comment by Globalrun** [comment] 2018-04-06 12:35
I got the same issue.

"Error: The page you are looking for cannot be displayed because an invalid method (HTTP verb) is being used."

**Comment by EricJizbaMSFT** [comment] 2018-04-06 16:47
What type of application are you deploying? Node, .NET Core, Static HTML?

And are you deploying to a Windows or Linux Web App in Azure?

**Comment by ekyros** [comment] 2018-04-06 20:28
Angular spa from vs code.  Windows server.  I get the error when deploying to the production slot.  I just started getting the error today.  I can deploy to a “stage” deployment slot and then swap slots.  Strange…

Brian Paul | President | 469-293-3079 x100
[EK-LogoResizedForEmail]

**Comment by nturinski** [comment] 2018-04-06 22:26
@ekyros, I've been trying to reproduce your bug, but I haven't succeeded yet.  Here's what are the steps that I've tried:

1.) Created a new Windows Web App
2.) Cloned this Angular SPA repo (https://github.com/gothinkster/angular-realworld-example-app)
3.) Ran `npm install`, `ng serve`, and `ng build`
4.) Deploy the "dist" folder via "zipdeploy"

Are there any steps that you are doing differently that might help me repro? Some other questions:

- Do you have any specific application settings that may be affecting deployment?
- What is the Deployment Source type of your web application?  And your "stage" deployment slot?  This can be found by right-clicking the respective node in the extension explorer and clicking `Configure Deployment Source`.

**Comment by ninianh** [comment] 2018-04-10 10:50
same issue here

**Comment by nturinski** [comment] 2018-04-10 21:42
@ekyros @Globalrun @ninianh 

We've been trying to repro this issue, but we haven't had any success yet.  It would be awesome if anybody could help us pinpoint this problem by trying to deploy using one of two methods:

1. If you have the Azure CLI installed, could you try to deploy to your web app using the following command:
`az webapp deployment source config-zip --name
                                       --resource-group
                                       --src
                                       [--slot]`
(reference: https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/source?view=azure-cli-latest#az-webapp-deployment-source-config-zip)

2.  If you could install a previous version of the Azure App Service Extension by manually installing this .vsix (https://github.com/Microsoft/vscode-azureappservice/releases/download/v0.6.1/vscode-azureappservice-0.6.1.vsix) and then attempt a deploy, it would tell us if the breaking changes are in v0.7.0 or if the changes were introduced somewhere else.

We're really sorry if this is blocking your web apps.  If you need to update your web app immediately, please try to use the Local Git Deployment Source or connect it to a GitHub repository.  This can be done in the "Configure Deployment Source" context action.

**Comment by nturinski** [comment] 2018-04-12 22:02
@ninarn Thanks for your help in testing this issue.  I'm able to repro this issue on a Linux container with a custom domain now as well.  I appreciate your time and hope to resolve this issue soon!

**Comment by nturinski** [comment] 2018-04-13 22:16
@ekyros @Globalrun @ninianh We released a new version of the extension today that will hopefully resolve this issue.  Please give it a try and let us know if you are still having issues deploying.

Thanks again for your assistance in tracking down the issue!

**Comment by ekyros** [comment] 2018-04-15 16:46
Sorry, I was out last week.  I installed the VS Code update and deployed my SPA/Angular app and it worked great.  No error.  Thank you!

Brian Paul | President | 469-293-3079 x100
[EK-LogoResizedForEmail]

**Comment by ninianh** [comment] 2018-04-16 04:01
@nturinski @ekyros New version, it works for me too. Thanks team.

**Comment by nturinski** [comment] 2018-04-16 22:36
@ekyros @ninianh I'm glad that this resolved your issue.  I'll go ahead and close this.

Thanks for your patience in this and for using the App Service Extension!

**Closed by nturinski** 2018-04-16 22:36 UTC
Labels: bug

**Comment by ekyros** [comment] 2018-04-16 22:37
Thank you!  I appreciate the quick resolution.  You guys are awesome!

Brian Paul | President | 469-293-3079 x100
[EK-LogoResizedForEmail]
