### ISSUE TITLE
Unable to SSH into AppService(Linux) from VSCODE

### ISSUE THREAD

**Issue by vijayraavi** [microsoft/vscode-azureappservice#1482] opened 2020-04-11 22:27 UTC
Does this occur consistently? YES
Repro steps:
1.Unable to SSH into AppService(Linux) from VSCODE

Action: appService.StartSsh
Error type: Error
Error Message: Unable to establish connection to application: App is started, but port is unreachable

Version: 0.16.5
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code - Insiders
Product Version: 1.44.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
TunnelProxy.<anonymous> extension.bundle.js:164:154308
rejected extension.bundle.js:164:149909
propagateAslWrapper async-listener/index.js:504:23
glue.js:188:31async-listener/glue.js:188:31
index.js:541:70async-listener/index.js:541:70
glue.js:188:31async-listener/glue.js:188:31
```
![Visual Studio Code - SSH](https://user-images.githubusercontent.com/11045643/79056228-c8c93680-7c71-11ea-8576-5c8362bab1fe.png)

</details>

**Comment by EricJizbaMSFT** [comment] 2020-04-13 17:54
Duplicate of https://github.com/microsoft/vscode-azureappservice/issues/1011. Only workaround at the moment is to use the portal

**Closed by EricJizbaMSFT** 2020-04-13 17:54 UTC
