### ISSUE TITLE
Failed to get status of deployment

### ISSUE THREAD

**Issue by emailnyaoki** [microsoft/vscode-azureappservice#1768] opened 2020-09-11 15:03 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.18.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:164:515775
rejected extension.bundle.js:164:515202
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment] 2020-09-11 17:57
Please provide repro steps.

**Comment by EricJizbaMSFT** [comment] 2020-09-12 00:03
Dupe of https://github.com/microsoft/vscode-azureappservice/issues/1425

**Closed by EricJizbaMSFT** 2020-09-12 00:03 UTC
Labels: needs more info
