### ISSUE TITLE
Deployment failed

### ISSUE THREAD

**Issue by frankfengnz** [microsoft/vscode-azureappservice#1691] opened 2020-07-10 12:39 UTC
Does this occur consistently? Yes
Repro steps:

1. In Visual Studio Code, right-click the folder "dist"
2. Choose "Deploy to Web App"
3. Press the button "Deploy" in the popup dialog.
4. show the message "Deploying to "xxxx"... Check output window for status."
5. a few minutes later, showing error information "There is a deployment currently in progress. Please try again when it completes."

6. use ssh tool to execute command "rm site/locks/deployment/info.lock", then redo step 1 to step 4. still get the error on step 5.

Action: appService.Deploy
Error type: 409
Error Message: There is a deployment currently in progress. Please try again when it completes.

Version: 0.17.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.47.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:309:399343extension.bundle.js:309:399343
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:584810
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by frankfengnz** [comment] 2020-07-10 21:41
20 hours passed still the same. I am sure no one doing deployment currently, and no CI/CD either. I checked it created an empty temporary folder in /home/site/deployments and a file called /home/site/locks/deployment/info.lock. But it still cannot proceed for some unknown reasons.

**Comment by EricJizbaMSFT** [comment] 2020-07-10 23:03
Closing as a dupe of https://github.com/microsoft/vscode-azureappservice/issues/1589. We've seen some other users with a similar situation like yours (there isn't actually a deployment going, but they still see this error), but unfortunately we don't have a solution yet. I don't know anything about the "info.lock" file you mentioned or if that makes a difference

Only workarounds are to create a new web app or contact Azure support directly.

**Closed by EricJizbaMSFT** 2020-07-10 23:03 UTC
