### ISSUE TITLE
Entry not found in cache.

### ISSUE THREAD

**Issue by robotob** [Microsoft/vscode-azureappservice#921] opened 2019-04-03 06:33 UTC
Repro steps:

1.
2.

Action: appService.Start
Error type: Error
Error Message: Entry not found in cache.

Version: 0.13.0
OS: win32
VS Code Version: 1.32.3

<details>
<summary>Call Stack</summary>

```
a.module.exports.a.createError (dist/extension.js:1:49013)
b.<anonymous> (dist/extension.js:229:176356)
dist/extension.js:229:170971
dist/extension.js:229:42963
dist/extension.js:229:40956
dist/extension.js:229:40578
i.module.exports.i.find (dist/extension.js:229:75071)
module.exports.find.init.then (dist/extension.js:229:22902)
```

</details>

**Comment by nturinski** [comment] 2019-04-11 22:51
Closing as a dupe of https://github.com/Microsoft/vscode-azureappservice/issues/430

**Closed by nturinski** 2019-04-11 22:51 UTC
