### ISSUE TITLE
ran into this while streaming logs

### ISSUE THREAD

**Issue by zulkarnain-shah** [Microsoft/vscode-azureappservice#556] opened 2018-08-09 08:43 UTC
Repro steps:
<Enter steps to reproduce issue>

Action: appService.Restart
Error type: Error
Error Message: unrecognized request

Version: 0.9.0
OS: darwin

**Comment by nturinski** [comment] 2018-08-23 21:05
Hi @zulkarnain-shah,

Thanks for reporting this issue.  I haven't been able to reproduce this.  Could you provide more details on how this error occurred?

**Comment by EricJizbaMSFT** [comment] 2018-09-19 18:04
Closing due to lack of info. Feel free to re-open with more info

**Closed by EricJizbaMSFT** 2018-09-19 18:04 UTC
Labels: bug, needs more info
