### ISSUE TITLE
Access token expiry utc time is earlier than current utc time?

### ISSUE THREAD

**Issue by FreddySSF** [microsoft/vscode-azureappservice#2483] opened 2023-05-14 19:52 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ExpiredAuthenticationToken
Error Message: The access redacted:key UTC time '5/14/redacted:id redacted:id PM' is earlier than current UTC time '5/14/redacted:id redacted:id PM'.

Version: 0.24.8
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
handleErrorResponse extension.bundle.js:2:1607519
deserializeResponseBody extension.bundle.js:2:1608250
```

</details>

**Comment by alexweininger** [comment] 2023-05-17 22:04
Duplicate of #2464, please follow that issue for future updates.

**Closed by alexweininger** 2023-05-17 22:04 UTC
