### ISSUE TITLE
There is an extra empty folder "_del_node_modules" in “Files” after executing "Redeploy"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1717] opened 2020-08-04 07:48 UTC
**OS:** Win10/Mac
**Build Version:** 20200730.4

**Repro Steps:**
1. Create a Trial Web App.
2. Expand "Deployments" node --> Right click the deployment --> Select "Redeploy".
3. Click "Refresh" button about three times after redeploying.
4. Check the "Files".

**Expect:**
There is no extra empty folder "_del_node_modules".

**Actual:**
There is an extra empty folder "_del_node_modules".
![image](https://user-images.githubusercontent.com/62053665/89264553-b1211e00-d665-11ea-8ed9-e1732e19651a.png)

**Comment by nturinski** [comment] 2020-08-04 20:50
Closing as a dupe of https://github.com/microsoft/vscode-azureappservice/issues/1717.  It's probably stemmed from the same issue.

**Closed by nturinski** 2020-08-04 20:50 UTC
Labels: AT-CTI

**Comment by v-mengwe** [comment] 2020-08-05 01:27
@nturinski  Is the duplicate link given wrong?

> Closing as a dupe of #1717. It's probably stemmed from the same issue.

**Comment by nturinski** [comment] 2020-08-05 18:19
@v-mengwe Yes! You're correct, thank you for verifying 😄
