### ISSUE TITLE
issue creating web app with sandbox subscription

### ISSUE THREAD

**Issue by karemf18** [microsoft/vscode-azureappservice#1603] opened 2020-06-17 21:19 UTC
The issue text was copied to the clipboard.  Please paste it into this window.

**Comment by karemf18** [comment] 2020-06-17 21:19
Does this occur consistently? 
Repro steps:


1.
2.

Action: appService.CreateWebApp
Error type: AuthorizationFailed
Error Message: The client 'live.com#karemfabrice@hotmail.com' with object id '706f193a-e0b1-4ab9-94d1-e99847081f67' does not have authorization to perform action 'Microsoft.Web/serverfarms/read' over scope '/subscriptions/ad6d4767-abfb-4459-938a-55a306750cfa/resourceGroups/appsvc_linux_centralus/providers/Microsoft.Web/serverfarms/appsvc_linux_centralus' or the scope is invalid. If access was recently granted, please refresh your credentials.

Version: 0.17.0
OS: darwin
OS Release: 19.5.0
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:3583434
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:584810
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-06-18 01:20
Dupe of https://github.com/microsoft/vscode-azureappservice/issues/1490. As a workaround, try "Advanced" create - which should give you more options that might work for your subscription

**Closed by EricJizbaMSFT** 2020-06-18 01:20 UTC
