### ISSUE TITLE
The subscription 'idsubscription' is not allowed to create or update the serverfarm.

### ISSUE THREAD

**Issue by antonello80pili** [microsoft/vscode-azureappservice#2634] opened 2024-04-21 17:28 UTC
I red about this issue, seems there is not fix about. Anithing we need to do to make it works? Or just need to try and hope to be lucky?

**Comment by alexweininger** [comment] 2024-04-22 16:33
Closing as a duplicate of #2635

**Closed by alexweininger** 2024-04-22 16:33 UTC
