### ISSUE TITLE
I don't understand

### ISSUE THREAD

**Issue by 88V** [microsoft/vscode-azureappservice#1964] opened 2021-02-13 17:07 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to https://simplicity502.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: socket hang up

Version: 0.20.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.53.2
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:327:22
TLSSocket.socketOnEnd _http_client.js:453:9
TLSSocket.emit events.js:327:22
endReadableNT _stream_readable.js:1220:12
processTicksAndRejections task_queues.js:84:21
```

</details>

**Comment by ejizba** [comment] 2021-02-16 18:12
Dupe of https://github.com/microsoft/vscode-azureappservice/issues/1932

**Closed by ejizba** 2021-02-16 18:12 UTC
