### ISSUE TITLE
issue create new web app

### ISSUE THREAD

**Issue by hendrik49** [microsoft/vscode-azureappservice#1974] opened 2021-02-20 09:41 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: AuthorizationFailed
Error Message: The client 'live.com#drikdoank@gmail.com' with object id '34c2ce10-1b51-4837-b83e-e7919c3dfe12' does not have authorization to perform action 'Microsoft.Web/serverfarms/read' over scope '/subscriptions/c55f733c-e49f-40c8-af2c-42f2e58ac23a/resourceGroups/appsvc_windows_centralus/providers/Microsoft.Web/serverfarms/appsvc_windows_centralus' or the scope is invalid. If access was recently granted, please refresh your credentials.

Version: 0.20.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.53.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:66146
extension.bundle.js:46:496611
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by ejizba** [comment] 2021-02-22 23:00
Dupe of https://github.com/microsoft/vscode-azureappservice/issues/1490

**Closed by ejizba** 2021-02-22 23:00 UTC
