### ISSUE TITLE
Node.js not supported on Windows in Azure

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureappservice#1346] opened 2020-01-06 10:14 UTC
**OS:** Win 10
**Build Version:** [20200105.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13432&view=results)
**Regression:** Previous Release (0.16.3)

**Repro Steps:**

1. Open the nodejs-docs-hello-world-master folder in VS Code.
2. Click the button "Deploy to Web App...".
3. Select a Windows Web App.
4. Click "Deploy" when asked "Are you sure you want to deploy to ...".
5. Browse website after deploying successfully --> Check the website.

**Expect:**
Display "Hello World".
![image](https://user-images.githubusercontent.com/57662131/71808941-f9656700-30a9-11ea-8fc4-a003a48c01dc.png)

**Actual:**
Display "HTTP 500 error".
![image](https://user-images.githubusercontent.com/57662131/71808892-d8047b00-30a9-11ea-8bd6-b572d5a462b5.png)

**More Info:**
This issue doesn't reproduce for python and C# project.

**Comment by nturinski** [comment] 2020-01-09 22:45
This was most likely just a temporary outage since this is a very mainline scenario.  Could you try this again and see if it reproduces?

**Comment by v-xinda** [comment] 2020-01-10 03:19
Verified on the latest build [20200109.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13570&view=results), this issue still reproduces for now. I will continue to track this issue.

**Comment by EricJizbaMSFT** [comment] 2020-02-11 21:22
I can repro this. Interestingly, the portal doesn't seem to support node.js on Windows. If I create a new app and select Node as the runtime, "Windows" is grayed out
![Screen Shot 2020-02-11 at 1 20 01 PM](https://user-images.githubusercontent.com/11282622/74280366-4b189700-4cd1-11ea-8ac0-a60eab7b729e.png)
If I try to change the runtime of an existing app, Node isn't listed:
![Screen Shot 2020-02-11 at 1 22 00 PM](https://user-images.githubusercontent.com/11282622/74280511-874bf780-4cd1-11ea-96d2-5c2c1ae6b2d4.png)

**Comment by v-xinda** [comment] 2020-02-13 07:36
Creating Web app and selecting Node as the runtime, then deploying and browsing website. More details get from the below chart.

Runtime   stack | Operating   System | Browse   website
-- | -- | --
Node 12   LTS | Linux&   Windows | Linux:   Display the symbol of Microsoft Azure.   Windows:   Display "You do not have permission to view this directory or   page".
Node 10   LTS | Linux | Display   the symbol of Microsoft Azure.
Node   10.14 | Linux&   Windows | Linux:   Display the symbol of Microsoft Azure.   Windows:   Display "You do not have permission to view this directory or   page".
Node   10.10 | Linux | Display   the symbol of Microsoft Azure.
Node   10.6 | Linux&   Windows | Linux:   Display the symbol of Microsoft Azure.   Windows:   Display "You do not have permission to view this directory or   page".
Node   10.1 | Linux | Display   the symbol of Microsoft Azure.
Node   10.0 | Windows | Display   "You do not have permission to view this directory or page".

Windows Web app website displayed
![image](https://user-images.githubusercontent.com/57662131/74409431-a5505e00-4e71-11ea-89c1-6b4bb7d0eccd.png)

Linux Web app website displayed
![image](https://user-images.githubusercontent.com/57662131/74409483-c1ec9600-4e71-11ea-99e7-66cb3d8e90bd.png)

**Comment by EricJizbaMSFT** [comment] 2020-05-20 19:23
Did some more testing and the portal _does_ allow node.js on windows now. And it works if I deploy to that app. _However_, it doesn't work if I deploy to an app created from our extension. I'm guessing it's because we don't ask for runtime version on windows and thus we never add the `WEBSITE_NODE_DEFAULT_VERSION` app setting

**Comment by nturinski** [comment] 2020-05-20 20:28
This might have been introduced by this PR: https://github.com/microsoft/vscode-azureappservice/pull/1106

**Comment by v-mengwe** [comment] 2020-10-10 10:02
Verified on the latest build 20201001.2.
**Repro Steps:**

1. Create a Windows web app.
2. Open the python-docs-hello-world folder in VS Code.
3. Deploy to this Windows Web App.
4. Check the result.

**Actual:**
Display "You do not have permission to view this directory or page".
![image](https://user-images.githubusercontent.com/62053665/95652150-b2693e00-0b21-11eb-8812-cd20b7623d08.png)

**More Info:**

1. Open this Windows web app in portal --> Configuration --> General settings --> Change the settings as follow --> Save.
 ![image](https://user-images.githubusercontent.com/62053665/95652269-69fe5000-0b22-11eb-8807-a98bda750872.png)
3. Deploy again.
3. Check the result.
![image](https://user-images.githubusercontent.com/62053665/95652294-9ade8500-0b22-11eb-984d-6296299b90ba.png)

**Comment by EricJizbaMSFT** [comment] 2020-11-06 22:11
Fixed in https://github.com/microsoft/vscode-azureappservice/pull/1835

**Closed by EricJizbaMSFT** 2020-11-06 22:11 UTC
Labels: AT-CTI
