### ISSUE TITLE
VSCode: ENOENT error when deploying war file via Azure App Service extension

### ISSUE THREAD

**Issue by bipinmangwani1** [microsoft/vscode-azureappservice#1128] opened 2019-09-04 16:47 UTC
Repro steps:

1. In VSCode -> go to Azure:app service extension
2. Expand the subscription
3. Right click the web app -> Deploy to Web App -> Select the war file

Action: appService.Deploy
Error type: Error
Error Message: spawn c:\dev\apps\VSCode1.37.1\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe ENOENT

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.t.deserializeSearchError workbench.main.js:4032:757
Promise.all.then.t workbench.main.js:4680:682
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment] 2019-09-05 15:45
Closing as dupe of https://github.com/microsoft/vscode-azureappservice/issues/1092

**Closed by nturinski** 2019-09-05 15:45 UTC
