### ISSUE TITLE
Azure app service, node app deploy faild.

### ISSUE THREAD

**Issue by yth0625** [microsoft/vscode-azureappservice#1934] opened 2021-01-21 13:58 UTC
Does this occur consistently? Yes

Repro steps:
1, I built and deployed my app to be able to start it with the `npm run start` command.

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to https://frontier-transfer-test.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET

Version: 0.20.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

I am trying to deploy my node app using web service.
However, the build keeps failing, and in the log stream,

> 2021-01-20T05:35:46.415Z ERROR-Container {my app name} didn't respond to HTTP pings on port: 8080, failing site start. See container logs for debugging.

An error occurs. Referring to the [link](https://techcommunity.microsoft.com/t5/apps-on-azure/things-you-should-know-web-apps-and-linux/ba-p/392472),
I tried to increase the container startup time by putting the `WEBSITES_CONTAINER_START_TIME_LIMIT` value, but the app service could not find a space to put the environment variable in the docker container. (I tried putting it as a general environment variable, but it was not entered.)

The command docker used when running:

> docker run -d -p 5132:8080 --name {contianer name} -e WEBSITE_SITE_NAME={app name} -e WEBSITE_AUTH_ENABLED=False -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME={WEBSITE_HOST_NAME} -e WEBSITE_INSTANCE_ID={WEBSITE_INSTANCE_ID} -e HTTP_LOGGING_ENABLED=1 appsvc/node:10-lts_20201112.3 npm run start

Should I use docker container to deploy the app service's node app?
Is there any way to deploy it in code?

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

**Comment by ejizba** [comment] 2021-02-01 23:06
Dupe of https://github.com/microsoft/vscode-azureappservice/issues/1932

**Closed by ejizba** 2021-02-01 23:06 UTC

**Comment by ejizba** [comment] 2021-02-01 23:07
The "ECONNRESET" bug should be fixable by just re-trying. I'm not super familiar with the rest of the info you mentioned, including `WEBSITES_CONTAINER_START_TIME_LIMIT`. I'm guessing that is most likely something specific to your app
