### ISSUE TITLE
Deployment Slots Issue

### ISSUE THREAD

**Issue by bercht-a** [Microsoft/vscode-azureappservice#565] opened 2018-08-15 11:52 UTC
Repro steps:
Tray to create a new deployment slot.
Same error when i expand the "Deplyoment Slots" Node in the tree-view

Action: appService.CreateSlot
Error type: ArgumentError
Error Message: Invalid Object.

Version: 0.9.0
OS: win32

**Comment by EricJizbaMSFT** [comment] 2018-08-15 18:11
Closing as duplicate of https://github.com/Microsoft/vscode-azureappservice/issues/564

**Closed by EricJizbaMSFT** 2018-08-15 18:11 UTC
Labels: P2, bug
