### ISSUE TITLE
teste

### ISSUE THREAD

**Issue by ludy1234** [microsoft/vscode-azureappservice#2525] opened 2023-06-25 12:56 UTC
Does this occur consistently? 
Repro steps:

[nodejs.zip](https://github.com/microsoft/vscode-azureappservice/files/11859752/nodejs.zip)

1.
2.

Action: appService.Deploy
Error type: 403
Error Message: Error 403 - Forbidden

The web app you have attempted to reach has blocked your access.

Version: 0.24.9
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.79.2
Language: pt-br

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547extension.bundle.js:2:1696547
```

</details>

**Comment by alexweininger** [comment] 2023-06-28 22:41
Closing as duplicate of #2526

**Closed by alexweininger** 2023-06-28 22:41 UTC
