### ISSUE TITLE
Opening server (Azure Web App) log files in vs code

### ISSUE THREAD

**Issue by capttaz1** [Microsoft/vscode-azureappservice#732] opened 2018-11-22 16:51 UTC
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.showFile
Error type: Error
Error Message: TextEditor(vs.editor.ICodeEditor:1,$model258) has been disposed

Version: 0.9.1
OS: darwin

**Comment by EricJizbaMSFT** [comment] 2018-11-26 16:45
Closing as duplicate of https://github.com/Microsoft/vscode-azureappservice/issues/611. We already have a fix in master and it should be released soon. Thanks!

**Closed by EricJizbaMSFT** 2018-11-26 16:45 UTC
