### ISSUE TITLE
TextEditor

### ISSUE THREAD

**Issue by CarlosTrujillo03** [Microsoft/vscode-azureappservice#715] opened 2018-11-17 19:17 UTC
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.showFile
Error type: Error
Error Message: TextEditor(vs.editor.ICodeEditor:1,$model38) has been disposed

Version: 0.9.1
OS: win32

**Comment by nturinski** [comment] 2018-11-19 20:49
Hi @CarlosTrujillo03,

Thanks for reporting this issue.  This issue should be resolved with our next release with this PR: https://github.com/Microsoft/vscode-azureappservice/pull/714.

This seems to be a duplicate of this issue: https://github.com/Microsoft/vscode-azureappservice/issues/611 so I'm going to close this issue as a dupe.  If that doesn't seem to be the case, please re-open the issue with more information to repro the bug.

Thanks!

**Closed by nturinski** 2018-11-19 20:49 UTC
Labels: duplicate
