### ISSUE TITLE
An error occurs in Azure view (Mooncake/Germany account) after opening a project in VS Code 

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#1806] opened 2020-10-14 09:52 UTC
**OS:** Windows 10
**Build Version:** 20201013.1

**Repro Steps:**
1. Sign in with Azure China Mooncake/Azure Germany account.
2. Create a web app.
3. Open a project in VS Code and check the Azure view

**Expect:**
Azure view shows well without any error.

**Actual:**
An error occurs in Azure view.
![image](https://user-images.githubusercontent.com/45614674/95972661-4e0ded80-0e45-11eb-9efb-c16fd03bc51c.png)

**Comment by EricJizbaMSFT** [comment] 2020-10-19 22:28
Dupe of https://github.com/microsoft/vscode-azure-account/issues/215. Should be fixed if you reload VS Code

**Closed by EricJizbaMSFT** 2020-10-19 22:28 UTC
Labels: AT-CTI

**Comment by v-mengwe** [comment] 2020-10-20 06:03
Verified on the latest build 202010109.1, this issue also reproduces after reloading VS Code.

More Info:
This issue doesn't reproduce when executing "Open a project in VS Code -> Sign in with Azure China Mooncake/Azure Germany account" actions.
