### ISSUE TITLE
Server hang up

### ISSUE THREAD

**Issue by abhinav17091994** [microsoft/vscode-azureappservice#1985] opened 2021-03-01 13:40 UTC
Does this occur consistently? 
Repro steps:

1. Tried to deploy app in dev environment but got the below mentioned error.
2. Is it related to azure app service ?

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to https://credituniondev.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: socket hang up

Version: 0.20.0
OS: win32
OS Release: 10.0.16299
Product: Visual Studio Code
Product Version: 1.53.2
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:327:22
ClientRequest.EventEmitter.emit domain.js:483:12
TLSSocket.socketOnEnd _http_client.js:453:9
TLSSocket.emit events.js:327:22
TLSSocket.EventEmitter.emit domain.js:483:12
endReadableNT _stream_readable.js:1220:12
processTicksAndRejections task_queues.js:84:21
```

</details>

**Comment by ejizba** [comment] 2021-03-01 22:12
Dupe of https://github.com/microsoft/vscode-azureappservice/issues/1932

**Closed by ejizba** 2021-03-01 22:12 UTC
