### ISSUE TITLE
Download app settings as local settings and upload to other web apps

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-azureappservice#386] opened 2018-04-04 22:44 UTC
Even though App Services doesn't have the concept of a `local.settings.json`, I thought it might be useful to be able to download app settings as a JSON and upload it to another web app in the same way Functions does.

**Comment by EricJizbaMSFT** [comment] 2018-10-12 20:29
Closing as duplicate of https://github.com/Microsoft/vscode-azureappservice/issues/639

**Closed by EricJizbaMSFT** 2018-10-12 20:29 UTC
Labels: P2, enhancement
