### ISSUE TITLE
Deleted app service/deployment slot is not removed from the explorer

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#107] opened 2017-10-03 21:30 UTC
The parent node _is_ refreshed, but the slot or app service is still there. It's almost like it's not waiting properly until deletion finishes to refresh the parent node

**Comment by whiskeyjay** [comment] 2017-10-03 22:52
Duplicate of #92

**Closed** 2017-10-04 00:07 UTC
Labels: duplicate
