### ISSUE TITLE
Deploy new Angular App to AppService 

### ISSUE THREAD

**Issue by mhpaf** [microsoft/vscode-azureappservice#1498] opened 2020-04-21 22:15 UTC
Does this occur consistently? YES
Repro steps:
1. Create new Project (ng new 'project')
2. Use VSCode with extension to publish to a web app 

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "ng-test-2" failed. See output channel for more details.

Version: 0.16.5
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:522593
fulfilled extension.bundle.js:1:519732
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-04-22 17:03
Closing as duplicate of https://github.com/microsoft/vscode-azureappservice/issues/1006. A simple angular app won't work out of the box on app service

**Closed by EricJizbaMSFT** 2020-04-22 17:03 UTC
