### ISSUE TITLE
'Cancel' doesn't work when deleting web apps

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#480] opened 2018-06-21 07:52 UTC
**Repro Steps:**
1. Right click one web and select 'Delete'.
2. Click 'Cancel' button on the prompting dialog, then check the result.

**Expect:**
'Cancel' works well and the action is canceled.

**Actual:**
'Cancel' doesn't work and the web app is deleted successfully.
![delete](https://user-images.githubusercontent.com/34729092/41705073-7bbe61a6-7527-11e8-8688-180df544363b.PNG)

**More Info:**
This issue also reproduces when deleting application settings.

**Comment by nturinski** [comment] 2018-06-21 23:06
@EricJizbaMSFT `result === undefined || result === DialogResponses.cancel` is returning false after clicking "Cancel" in the prompt in AzureUserInput.  I messed around with other DialogResponses and they don't seem to resolve to true either.  Confirmed that it works when comparing `result.title === DialogResponses.cancel.title`. 

I don't think that this is a new change though.  Any ideas?

**Comment by EricJizbaMSFT** [comment] 2018-06-22 17:00
It's probably because this repo has been updated to use 0.15.0 of the ui package, but the appservice package is still referencing 0.13.0 (Stephen updated the repo, but we haven't published the new package yet). Should be fixed once that new package is published

**Comment by StephenWeatherford** [comment] 2018-06-22 18:08
Why does this matter?  Isn't the prompt passed in the one that's returned?  This is a dangerous situation if a mismatched version can cause data loss.

**Comment by EricJizbaMSFT** [comment] 2018-06-22 18:24
The canceled case is a little different because we're checking for it within AzureUserInput rather than returning it https://github.com/Microsoft/vscode-azuretools/blob/master/ui/src/AzureUserInput.ts#L65.

We should probably change that logic just to be safe (@nturinski's `.title` thing would probably work), but we should never be shipping with two different versions of the ui package because that could lead to a lot of weirdness (Keep in mind this is only a problem when someone makes breaking changes to the ui package - it's not a problem for patch updates because we don't require specific patch versions)

**Comment by StephenWeatherford** [comment] 2018-06-22 21:58
Yeah, I'm going to suggest that this is a bad idea.  Normally we shouldn't ever compare messages, but instead keys or codes.  I haven't worried about it before because the message being passed and checked has been completely local.

Even with Nathan's title fix, it could fail with localization or changed messages.

Might I suggest:
1) [easiest] Have showWarningMessage not throw user canceled (personally, not sure I like the different behavior in this interface for the vscode method it wraps)
2) Have showMessageMessage automatically add the cancel option (if necessary have a different function for those that are specifically cancelable, or else pass in an isCancelable flag)

**Comment by nturinski** [comment] 2018-06-27 21:44
As this is resolved in the App Service extension by updating the packages, I will close the issue on the App Service repo and open an issue in the azuretools repo since the problem originates there.

**Closed by nturinski** 2018-06-27 21:44 UTC
Labels: CTI
