### ISSUE TITLE
Zip & Deploy function does not display all web apps in quick picks

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-azureappservice#67] opened 2017-09-19 17:33 UTC
All of my apps do not appear in the quick pick prompt.  At the cited lines, it is checking for Linux and app, however my app appears to only have 'app' in its kind field instead of 'app,linux'

https://github.com/Microsoft/vscode-azureappservice/blob/b5b415525d5195c6696e007234fddbd1854aa417/src/webAppZipPublisher.ts#L175-L176

![all apps do not show up](https://user-images.githubusercontent.com/5290572/30606169-a63d7cee-9d25-11e7-85ff-38486a0fd79d.PNG)

**Comment by whiskeyjay** [comment] 2017-09-20 17:38
This is by design, currently we are only targeting Linux web apps.

**Comment by michaeltlombardi** [comment] 2017-11-17 16:18
This seems like an easy place to remove the validator and add a warning to the effect of

> Hey, we're only investing development effort into the Linux web apps side right now, so here be dragons if you want to use this with a web app running on Windows - PR's accepted! 😄

**Comment by StephenWeatherford** [comment] 2017-11-18 09:11
I agree, seems like either we should support windows apps or make it clear we don't.

**Comment by EricJizbaMSFT** [comment] 2017-11-27 22:38
This has been merged. We will display linux and windows web apps on deploy See #183

**Closed by EricJizbaMSFT** 2017-11-27 22:38 UTC
Labels: bug
