### ISSUE TITLE
Make "check output" notifications actionable or provide option to show output

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azureappservice#643] opened 2018-10-12 18:05 UTC
> When a deployment kicks off, a notification pops up telling you to see the output pane for logs. It would be great if that notification was clickable -- allowing you to take action on it to immediately go to the output pane with the correct output source already selected. If that's not possible, it may be reasonable to just pop up the correct output pane every time a deployment starts, and allow you to turn that on/off as a preference.

I've heard this feedback quite a few times in the last week or so. Some people want to see the output by default so it may make sense to add a configuration to automatically show the output on long running tasks.

**Comment by EricJizbaMSFT** [comment] 2018-10-24 17:53
Dupe of #645

**Closed by EricJizbaMSFT** 2018-10-24 17:53 UTC
