### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'portalUrl') 

### ISSUE THREAD

**Issue by tushaar9027** [microsoft/vscode-azureappservice#2306] opened 2022-08-17 14:29 UTC
Upon deploying an app service, I see the following error:

Cannot read properties of undefined (reading 'portalUrl') (once i import spacy this error comes)

**Comment by nturinski** [comment] 2022-08-17 19:46
Duplicate of https://github.com/microsoft/vscode-azureappservice/issues/2288#issuecomment-1218077305

A fix for this is merged, but not released yet. If you need it urgently, you can download a custom vsix from here: https://dev.azure.com/ms-azuretools/534e1e1c-b364-44d0-b5ee-dce879a5106e/_apis/build/builds/50748/artifacts?artifactName=vsix&api-version=7.0&%24format=zip

**Closed by nturinski** 2022-08-17 19:46 UTC
