### ISSUE TITLE
Cannot SSH to app service

### ISSUE THREAD

**Issue by songpr** [microsoft/vscode-azureappservice#1291] opened 2019-11-15 09:40 UTC
Repro steps:

1.
2.

Action: appService.StartSsh
Error type: Error
Error Message: Unable to establish connection to application: App is started, but port is unreachable

Version: 0.16.1
OS: linux
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

<details>
<summary>Call Stack</summary>

```
TunnelProxy.<anonymous> extension.bundle.js:157:99743
a extension.bundle.js:157:95441
```

</details>

**Comment by nturinski** [comment] 2019-11-15 19:33
Hi @songpr 

Is this consistently happening?  Could you try connecting to SSH via the Portal?

**Comment by nturinski** [comment] 2019-11-21 23:24
Closing as dupe of https://github.com/microsoft/vscode-azureappservice/issues/1011

**Closed by nturinski** 2019-11-21 23:24 UTC
Labels: needs more info
