### ISSUE TITLE
Port is unreachable? I dont understand

### ISSUE THREAD

**Issue by justindstauffer** [microsoft/vscode-azureappservice#1397] opened 2020-02-17 18:43 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.StartRemoteDebug
Error type: Error
Error Message: Unable to establish connection to application: App is started, but port is unreachable

Version: 0.16.2
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
TunnelProxy.<anonymous> extension.bundle.js:157:323205
a extension.bundle.js:157:318903
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-02-18 18:12
Duplicate of https://github.com/microsoft/vscode-azureappservice/issues/1011

**Closed by EricJizbaMSFT** 2020-02-18 18:12 UTC
