### ISSUE TITLE
unable to create another web App from Vs code

### ISSUE THREAD

**Issue by sr185246** [microsoft/vscode-azureappservice#1978] opened 2021-02-22 08:26 UTC
Does this occur consistently?  Yes

Action: appService.CreateWebAppAdvanced
Error type: ECONNRESET
Error Message: request to https://management.azure.com/subscriptions/<subsctiptionID>/resourcegroups?api-version=2019-10-01 failed, reason: Client network socket disconnected before secure TLS connection was established

Version: 0.20.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.53.2
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:327:22
TLSSocket.socketErrorListener _http_client.js:426:9
TLSSocket.emit events.js:315:20
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:84:21
```

</details>

**Comment by ejizba** [comment] 2021-02-22 20:08
Dupe of https://github.com/microsoft/vscode-azureappservice/issues/1932

**Closed by ejizba** 2021-02-22 20:08 UTC
