### ISSUE TITLE
Error - open requirements 

### ISSUE THREAD

**Issue by GuilhermeFreitasIT** [microsoft/vscode-azureappservice#1927] opened 2021-01-17 21:41 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.openFile
Error type: Error
Error Message: cannot open azureAppService:/requirements.txt?id%3D%2Fsubscriptions%2Fea61b910-f5ac-4a97-954d-c96c562e1d10%2FresourceGroups%2Fappsvc_linux_centralus%2Fproviders%2FMicrosoft.Web%2Fsites%2FAPIDEHEUS%2FFiles%2Frequirements.txt. Detail: File seems to be binary and cannot be opened as text

Version: 0.20.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:6800:388
```

</details>

**Comment by ejizba** [comment] 2021-01-19 19:33
Duplicate of https://github.com/microsoft/vscode-azureappservice/issues/1740

**Closed by ejizba** 2021-01-19 19:33 UTC
