### ISSUE TITLE
Failed to get status of deployment

### ISSUE THREAD

**Issue by elisaper** [microsoft/vscode-azureappservice#1451] opened 2020-03-24 08:09 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.16.3
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.43.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:288:373764
rejected extension.bundle.js:288:373312
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-03-24 18:48
Dupe of https://github.com/microsoft/vscode-azureappservice/issues/1425

**Closed by EricJizbaMSFT** 2020-03-24 18:48 UTC
