### ISSUE TITLE
An error occurs when clicking on a file under the "Files" Node

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#2230] opened 2022-04-25 07:46 UTC
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32
**App Service Extension Build Version:** 20220421.6
**Regression:** Not a regression

**Repro Steps:**

1. Create a web app -> Deploy a project to it.
2. Expand the "Files" Node -> Click on a file under the "Files" Node.
3. Check whether opens the clicked file without any error or not.

**Expect:**
Open the clicked file without any error.

**Actual:**
An error occurs.
<img width="434" alt="Screen Shot 2022-04-25 at 15 41 05" src="https://user-images.githubusercontent.com/62053665/165042651-ddd8e8e6-3261-4023-8593-517c9551cd70.png">

**Comment by alexweininger** [comment] 2022-04-25 20:46
I think this bug is caused by how we changed generating the group tree item ids

**Comment by alexweininger** [comment] 2022-04-25 23:10
Fixed by https://github.com/microsoft/vscode-azureresourcegroups/pull/204

**Closed by alexweininger** 2022-04-25 23:10 UTC
Labels: bug, AT-CTI, unified
